### PR TITLE
Cs/#996 costs

### PR DESCRIPTION
**Pull request by colinsheppard**
Cost types are all now separate fields within the PersonCostEvent:

- rawCost: includes fare and/or fuel cost
- tollCost: for road pricing
- subsidy: from mode subsidy
- netCost: rawCost + tollCost - subsidy

Note, that "totalCost" in summaryStats is based on netCost.

Fuels costs are also now present in rawCost for driving.

Tolls are accumulated over whole trip (not just the last leg) and passed back via PassengerScheduleEmpty message.

Finally, tolls are not needed in a separate event, they are in PathTraversal "tollPaid" and can be summed over all such events to know total tolls paid to transportation authority.

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/997)

### CODE REVIEW

**Comment by colinsheppard** [comment]
test!

**Comment by michaz** [comment]
This was blocked by #1012, reviewing this right now.

**Comment by colinsheppard** [comment]
@michaz thanks for catching the toll issue. I was confused because when a route is EmbodiedWithCurrentTravelTime, the tolls are currently ignored, so I mistakenly thought that was happening everywhere.

Fixing soon.

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Pull request merged**
