### PR TITLE
RideHail name in OD skim

### PR DESCRIPTION
**Pull request by dimaopen**
Changes in ODSkims
1. Differentiate RIDE_HAIL and RIDE_HAIL_POOLED modes by ridehail name.
2. Empty ridehail name ("") in skims means generic (all fleets) value
3. This data is also written to skim csv files.
4. skimsODExcerpt.csv contains only generic ridehail data
5. Background skim generator generates only generic skim data

### CODE REVIEW

**Comment by jlaz** [comment]
The issue regarding the relative estimated costs of ride_hail vs ride_hail_pooled within rideHailMaster seems to be addressed. However, there is still an issue with the cost of ride_hail not appearing to reflect the specific costs of each rideHail manager.

**Comment by dimaopen** [comment]
Test!

**Comment by jlaz** [comment]
reviewed

**Review by jlaz — APPROVED** [review]

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
