### PR TITLE
Ak/#2624 merge urbansim

### LINKED ISSUE #2624: Censul block level reader from UrbanSim
image

UrbanSim_CensusBlock
Link to original diagram (please, feel free to update it accordingly): https://drive.google.com/file/d/1w3KErCWCCu5g8XUOcK8O131GQfltjtE3/view?usp=sharing

### PR DESCRIPTION
**Pull request by YOxan**
Closes #2624 

Preliminary version of merger

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2635)

### CODE REVIEW

**Comment by JustinPihony** [comment]
Rather than relying on the label, could you change this to be a draft?

**Comment by YOxan** [comment]
Sure, done.

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
