### PR TITLE
Router performance

### PR DESCRIPTION
**Pull request by michaz**
This refactors the router so that no superfluous work is done.

I basically looked at all the different access/egress/both-cases in detail, and assured that we only compute things we really want to know.

Plus, I stop looking for access and egress stations when I pass my final destination doing so. It's unlikely we want to walk to a transit stop longer than we would walk to the destination.

There's more, but I think returns are diminishing now. Pure population routing is down by approx. 20%, but that doesn't seem to translate to 20% faster runs, unfortunately.

EDIT: Or maybe it does. SfLight 0.5k went from 4 minutes to 3 minutes.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2030)

### CODE REVIEW

**Comment by michaz** [comment]
test!

**Comment by colinsheppard** [comment]
Just tested urbansim-10k scenario and first iteration run time went from 12 minutes to 9 minutes, so consistent with your 1k test. Will try a production run as a further test before doing a final review / acceptance.

**Comment by colinsheppard** [comment]
@michaz when running smart-baseline production scenario I'm getting this error:

`java.lang.IllegalStateException: No valid itineraries found for path computed in RaptorWorker
	at com.conveyal.r5.profile.StatsCalculator.computeStatistics(StatsCalculator.java:73)
	at com.conveyal.r5.profile.PathWithTimes.computeStatistics(PathWithTimes.java:179)
	at com.conveyal.r5.profile.PathWithTimes.computeTimes(PathWithTimes.java:146)
	at com.conveyal.r5.profile.PathWithTimes.<init>(PathWithTimes.java:42)
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.lambda$getPaths$6(McRaptorSuboptimalPathProfileRouter.java:244)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.conveyal.r5.profile.McRaptorSuboptimalPathProfileRouter.getPaths(McRaptorSuboptimalPathProfileRouter.java:243)
	at beam.router.r5.R5Wrapper.$anonfun$calcRoute$21(R5RoutingWorker.scala:747)
	at beam.sim.metrics.MetricsSupport.latency(MetricsSupport.scala:37)
	at beam.sim.metrics.MetricsSupport.latency$(MetricsSupport.scala:35)
	at beam.router.r5.R5Wrapper.latency(R5RoutingWorker.scala:241)
	at beam.router.r5.R5Wrapper.calcRoute(R5RoutingWorker.scala:731)
	at beam.router.r5.R5RoutingWorker$$anonfun$receive$1.$anonfun$applyOrElse$2(R5RoutingWorker.scala:199)
	at beam.sim.metrics.MetricsSupport.latency(MetricsSupport.scala:37)
	at beam.sim.metrics.MetricsSupport.latency$(MetricsSupport.scala:35)
	at beam.router.r5.R5RoutingWorker.latency(R5RoutingWorker.scala:69)
	at beam.router.r5.R5RoutingWorker$$anonfun$receive$1.$anonfun$applyOrElse$1(R5RoutingWorker.scala:199)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by colinsheppard** [comment]
Still, smart-baseline comparison first iteration:

sfbay-production-develop: XX min
production-sfbay-develop-test-routerperf: 75 min

**Comment by michaz** [comment]
Thanks!!

**Comment by michaz** [comment]
Ah yes, that's a (to me) mysterious exception from R5, probably best translated to "no route". Was caught previously, is caught again now.

**Comment by michaz** [comment]
test!

**Pull request merged**
