### PR TITLE
Utility notebook: simulations cost analysis update

### PR DESCRIPTION
**Pull request by nikolayilyin**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3706)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test!

**Review by dimaopen — APPROVED** [review]

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
