### PR TITLE
Docker: beam-environment and pilates-environment image updates

### PR DESCRIPTION
**Pull request by nikolayilyin**
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3820)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test!

**Review by dimaopen — APPROVED** [review]

**Pull request merged**
