### PR TITLE
Ccaldas/#2001 warmstart singleton 4ci

### LINKED ISSUE #2001: Make warmstart singleton
In order to avoid multiple downloads and multiple files processing

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #2001 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2002)

### CODE REVIEW

**Comment by carloscaldas** [comment]
test!

**Comment by JustinPihony** [comment]
@carloscaldas Is this still needed?

**Comment by JustinPihony** [comment]
Is this still needed - should we close it out or clean it up and push it through?

**Comment by JustinPihony** [comment]
Test!

**Comment by JustinPihony** [comment]
Error for posterity

> 01:36:54 /home/ubuntu/workspace/beam-forced-prs@2/src/main/scala/beam/router/R5RoutingApp.scala:79: not found: type TravelTimeCalculatorConfigGroup
> 01:36:54     val maxHours: Int = BeamWarmStart.maxHoursFromCalculator(new TravelTimeCalculatorConfigGroup)
> 01:36:54                                                                  ^
> 01:36:59 one error found

**Comment by carloscaldas** [comment]
Closed in favor of this one: https://github.com/LBNL-UCB-STI/beam/pull/2780

**Pull request closed without merging**
