### PR TITLE
Fix TravelTimeObserved related tests

### PR DESCRIPTION
**Pull request by JustinPihony**
Pushing to master since it is currently broken and requires this to work again

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1722)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
