### PR TITLE
generate conditional work start time / duration distribution for Austin and the whole U.S. 

### PR DESCRIPTION
**Pull request by zneedell**
addresses #2353

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2361)

### CODE REVIEW

**Comment by JustinPihony** [comment]
Test!

**Comment by JustinPihony** [comment]
@zneedell Can this be merged?

**Comment by zneedell** [comment]
@REASY do we want all of these scripts in Develop?

**Comment by REASY** [comment]
@zneedell yes, let's merge it. Is it possibly to remove CSV files and make a path to input CSV files as input args for the python script with some examples for the run?

**Pull request merged**
