### PR TITLE
#2336 - Add averageCarSpeed.png

### PR DESCRIPTION
**Pull request by SHaaD94**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2337)

### CODE REVIEW

**Comment by REASY** [comment]
@SHaaD94 could you, please, attach new graphs to see how they look visually?

**Comment by SHaaD94** [comment]
@REASY
image

**Comment by REASY** [comment]
@SHaaD94 it looks good. One minor thing (even though the task says add png file) - could you, please, write CSV file with speed so it is easier to do analysis using Python/Scala?

**Comment by SHaaD94** [comment]
@REASY, done
Example of csv data:
```
iteration,car_type,speed
1,Average,15.563189932421459
1,Personal,15.376134419202039
1,CAV,15.379770114942525
1,RideHail,15.933665263119815
2,Average,14.456559533735998
2,Personal,11.62435166289476
2,CAV,15.349001964636539
2,RideHail,16.39632497367669
3,Average,15.164516443416554
3,Personal,13.994093226813087
3,CAV,15.35284798342479
3,RideHail,16.14660812001179

```

**Comment by REASY** [comment]
@SHaaD94 seems like there should be an adjustment to the way how stats are computed for CAVs. 
In case of normal personal CARs, every ride consists of two phrases: driving and parking. But CAVs do not park.
If you run scenario [sf-light-10k.conf](https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/sf-light-10k.conf) with the following change on the line [sf-light-10k.conf#L134](https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/sf-light-10k.conf#L134)
```
beam.agentsim.agents.rideHail.allocationManager.name="POOLING_ALONSO_MORA"
```
you will start getting the following warnings:
```
01:12:16.095 WARN  b.a.c.CarRideStatsFromPathTraversalEventHandler$ - arrivalTime != departureTime
	driving: 	<event time="24629.0" type="PathTraversal" vehicle="3525-0" driver="cavDriver-3525-0" vehicleType="CAV" length="9831.166000000003" numPassengers="1" departureTime="24120" arrivalTime="24629" mode="car" links="32455,75021,75019,75017,75015,75013,75011,75009,89271,89267,47579,47577,89263,47575,89259,47573,47571,47569,32473,32471,32469,32467,32465,70295,32367,32416,82290,32296,82276,32422,32458,82268,82260,26828,74314,55576,55578,55598,55600,55602,55604,55606,54748,87760,54750,54752,75224,75226,75228,55620,87672,19268,70108,51980,51982,70046,70044,24994,78702,87658,78704,93983,70065,89749,93987,70063,89753,70061,70059,89765,89769,70053,24993,24991,24989,70051,70057,89781,70055,24980,89784,24982,24984,24986,35121,35119,82095,25021,82087,25019,82091,25025,25023,65825,18795,18793,18791,18789,18787,18759,3714,36286,36298,36300,68876,93414,89040,68878,19448,19450,19452,19454,19456,48247,48245,69993,48243,63033,22747,22745,22743,94217,22741,22739,18185,82017,18183,82025,18181,18179,82021,18177,18175,82033,18173,76839,82029,49913,49911,82067,49909,82063,49907,49905,49903,49901,49899,49897,49895,49893,68949,68947,68945,68943,71177,71175,71173,82059,71171,71169,71167,71157,71155,71153,71151,82013,82009,49919,49917,82049,49915,21169,21167,82055,21165,21163,46975,94079,46977,63877,63875,94083,75295,68957,55071,55069,94107" linkTravelTime="1.0,4.0,15.0,4.0,9.0,5.0,2.0,19.0,1.0,3.0,1.0,4.0,4.0,1.0,1.0,4.0,4.0,4.0,2.0,3.0,4.0,3.0,1.0,2.0,1.0,8.0,1.0,8.0,1.0,8.0,2.0,6.0,1.0,4.0,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,4.0,1.0,4.0,1.0,1.0,4.0,4.0,4.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,4.0,1.0,1.0,3.0,1.0,4.0,4.0,3.0,1.0,1.0,1.0,3.0,2.0,5.0,1.0,3.0,3.0,2.0,1.0,4.0,4.0,3.0,3.0,5.0,5.0,1.0,4.0,1.0,3.0,1.0,2.0,3.0,2.0,4.0,3.0,2.0,10.0,3.0,4.0,3.0,1.0,4.0,4.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,3.0,3.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,4.0,4.0,1.0,1.0,1.0,1.0,6.0,2.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,4.0,3.0,1.0,1.0,2.0,3.0,7.0,1.0,1.0,2.0,4.0,4.0,1.0,1.0,3.0,3.0,4.0,1.0,4.0,4.0,1.0,3.0,4.0,4.0,1.0,3.0,4.0,4.0,1.0,2.0,2.0,2.0,3.0,3.0" primaryFuelType="Gasoline" secondaryFuelType="None" primaryFuel="3.594254627267999E7" secondaryFuel="0.0" capacity="4" startX="-122.4858616" startY="37.7482209" endX="-122.3970085" endY="37.7664337" primaryFuelLevel="3.62003745372732E9" secondaryFuelLevel="0.0" seatingCapacity="4" tollPaid="0.0"  />
	parking: 	<event time="25849.0" type="PathTraversal" vehicle="3525-0" driver="cavDriver-3525-0" vehicleType="CAV" length="9717.755000000005" numPassengers="0" departureTime="25336" arrivalTime="25849" mode="car" links="94106,55068,55070,68956,75294,94082,63874,63876,46976,94078,46974,21162,21164,82054,21166,21168,49914,82048,49916,49918,82008,82012,71150,71152,71154,71156,71166,71168,71170,82058,71172,71174,71176,68942,68944,68946,68948,49892,49894,49896,49898,49900,49902,49904,49906,82062,49908,82066,49910,49912,82028,76838,18172,82032,18174,18176,82020,18178,18180,82024,18182,82016,18184,22738,22740,94216,22742,22744,22746,63032,48242,69992,48244,48246,69994,69996,69998,26976,19444,19446,89006,71088,71090,18760,93060,18762,39474,82108,39476,18758,18786,18788,18790,18792,18794,65824,25022,25024,82090,25018,82086,25020,82094,35118,35120,24987,24985,24983,89785,24981,70054,89780,70056,70050,24988,24990,24992,70052,89768,89764,70058,70060,89752,70062,93986,89748,70064,93982,78705,87659,78703,24995,70045,70047,51983,51981,70109,19269,41338,41340,41342,87668,41344,41346,41348,55614,55616,87756,55618,54756,54758,55608,55610,55612,55594,55596,54766,54768,26830,4368,4369,31724,31726,82264,82272,32300,32410,82280,82286,32486,32488,70294,32464,32466,32468,32470,32472,47568,47570,47572,89258,47574,89262,47576,47578,89266,89270,75008,75010,75012,75014,75016,75018,75020,32454,32455" linkTravelTime="3.0,3.0,2.0,2.0,2.0,1.0,4.0,4.0,3.0,1.0,4.0,4.0,3.0,1.0,4.0,4.0,1.0,4.0,3.0,3.0,1.0,1.0,4.0,4.0,2.0,1.0,1.0,7.0,3.0,2.0,1.0,1.0,3.0,4.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,1.0,2.0,6.0,1.0,1.0,1.0,1.0,4.0,4.0,1.0,1.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,2.0,1.0,1.0,1.0,7.0,1.0,1.0,3.0,4.0,3.0,10.0,2.0,3.0,4.0,2.0,3.0,2.0,1.0,3.0,1.0,4.0,1.0,5.0,5.0,3.0,3.0,4.0,4.0,1.0,2.0,3.0,3.0,1.0,5.0,2.0,3.0,1.0,1.0,1.0,3.0,4.0,4.0,1.0,3.0,1.0,1.0,4.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,3.0,4.0,4.0,1.0,1.0,3.0,1.0,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,2.0,7.0,1.0,8.0,1.0,7.0,1.0,8.0,1.0,2.0,1.0,3.0,4.0,3.0,2.0,4.0,4.0,4.0,1.0,1.0,4.0,4.0,1.0,3.0,1.0,19.0,2.0,5.0,9.0,4.0,15.0,4.0,1.0,1.0" primaryFuelType="Gasoline" secondaryFuelType="None" primaryFuel="3.5527917924899966E7" secondaryFuel="0.0" capacity="4" startX="-122.3970085" startY="37.7664337" endX="-122.4857432" endY="37.7482262" primaryFuelLevel="3.58450953580242E9" secondaryFuelLevel="0.0" seatingCapacity="4" tollPaid="0.0"  />
```
The warnings comes from the line [CarRideStatsFromPathTraversalEventHandler.scala#L352](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/analysis/cartraveltime/CarRideStatsFromPathTraversalEventHandler.scala#L352)

**Comment by SHaaD94** [comment]
> @SHaaD94 seems like there should be an adjustment to the way how stats are computed for CAVs.
> In case of normal personal CARs, every ride consists of two phrases: driving and parking. But CAVs do not park.
> If you run scenario [sf-light-10k.conf](https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/sf-light-10k.conf) with the following change on the line [sf-light-10k.conf#L134](https://github.com/LBNL-UCB-STI/beam/blob/develop/test/input/sf-light/sf-light-10k.conf#L134)
> 
> ```
> beam.agentsim.agents.rideHail.allocationManager.name="POOLING_ALONSO_MORA"
> ```
> 
> you will start getting the following warnings:
> 
> ```
> 01:12:16.095 WARN  b.a.c.CarRideStatsFromPathTraversalEventHandler$ - arrivalTime != departureTime
> 	driving: 	<event time="24629.0" type="PathTraversal" vehicle="3525-0" driver="cavDriver-3525-0" vehicleType="CAV" length="9831.166000000003" numPassengers="1" departureTime="24120" arrivalTime="24629" mode="car" links="32455,75021,75019,75017,75015,75013,75011,75009,89271,89267,47579,47577,89263,47575,89259,47573,47571,47569,32473,32471,32469,32467,32465,70295,32367,32416,82290,32296,82276,32422,32458,82268,82260,26828,74314,55576,55578,55598,55600,55602,55604,55606,54748,87760,54750,54752,75224,75226,75228,55620,87672,19268,70108,51980,51982,70046,70044,24994,78702,87658,78704,93983,70065,89749,93987,70063,89753,70061,70059,89765,89769,70053,24993,24991,24989,70051,70057,89781,70055,24980,89784,24982,24984,24986,35121,35119,82095,25021,82087,25019,82091,25025,25023,65825,18795,18793,18791,18789,18787,18759,3714,36286,36298,36300,68876,93414,89040,68878,19448,19450,19452,19454,19456,48247,48245,69993,48243,63033,22747,22745,22743,94217,22741,22739,18185,82017,18183,82025,18181,18179,82021,18177,18175,82033,18173,76839,82029,49913,49911,82067,49909,82063,49907,49905,49903,49901,49899,49897,49895,49893,68949,68947,68945,68943,71177,71175,71173,82059,71171,71169,71167,71157,71155,71153,71151,82013,82009,49919,49917,82049,49915,21169,21167,82055,21165,21163,46975,94079,46977,63877,63875,94083,75295,68957,55071,55069,94107" linkTravelTime="1.0,4.0,15.0,4.0,9.0,5.0,2.0,19.0,1.0,3.0,1.0,4.0,4.0,1.0,1.0,4.0,4.0,4.0,2.0,3.0,4.0,3.0,1.0,2.0,1.0,8.0,1.0,8.0,1.0,8.0,2.0,6.0,1.0,4.0,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,4.0,1.0,4.0,1.0,1.0,4.0,4.0,4.0,1.0,2.0,3.0,2.0,2.0,2.0,2.0,3.0,1.0,2.0,2.0,4.0,1.0,1.0,3.0,1.0,4.0,4.0,3.0,1.0,1.0,1.0,3.0,2.0,5.0,1.0,3.0,3.0,2.0,1.0,4.0,4.0,3.0,3.0,5.0,5.0,1.0,4.0,1.0,3.0,1.0,2.0,3.0,2.0,4.0,3.0,2.0,10.0,3.0,4.0,3.0,1.0,4.0,4.0,2.0,1.0,1.0,1.0,1.0,7.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,3.0,3.0,2.0,2.0,3.0,1.0,1.0,1.0,1.0,4.0,4.0,1.0,1.0,1.0,1.0,6.0,2.0,1.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,2.0,4.0,3.0,1.0,1.0,2.0,3.0,7.0,1.0,1.0,2.0,4.0,4.0,1.0,1.0,3.0,3.0,4.0,1.0,4.0,4.0,1.0,3.0,4.0,4.0,1.0,3.0,4.0,4.0,1.0,2.0,2.0,2.0,3.0,3.0" primaryFuelType="Gasoline" secondaryFuelType="None" primaryFuel="3.594254627267999E7" secondaryFuel="0.0" capacity="4" startX="-122.4858616" startY="37.7482209" endX="-122.3970085" endY="37.7664337" primaryFuelLevel="3.62003745372732E9" secondaryFuelLevel="0.0" seatingCapacity="4" tollPaid="0.0"  />
> 	parking: 	<event time="25849.0" type="PathTraversal" vehicle="3525-0" driver="cavDriver-3525-0" vehicleType="CAV" length="9717.755000000005" numPassengers="0" departureTime="25336" arrivalTime="25849" mode="car" links="94106,55068,55070,68956,75294,94082,63874,63876,46976,94078,46974,21162,21164,82054,21166,21168,49914,82048,49916,49918,82008,82012,71150,71152,71154,71156,71166,71168,71170,82058,71172,71174,71176,68942,68944,68946,68948,49892,49894,49896,49898,49900,49902,49904,49906,82062,49908,82066,49910,49912,82028,76838,18172,82032,18174,18176,82020,18178,18180,82024,18182,82016,18184,22738,22740,94216,22742,22744,22746,63032,48242,69992,48244,48246,69994,69996,69998,26976,19444,19446,89006,71088,71090,18760,93060,18762,39474,82108,39476,18758,18786,18788,18790,18792,18794,65824,25022,25024,82090,25018,82086,25020,82094,35118,35120,24987,24985,24983,89785,24981,70054,89780,70056,70050,24988,24990,24992,70052,89768,89764,70058,70060,89752,70062,93986,89748,70064,93982,78705,87659,78703,24995,70045,70047,51983,51981,70109,19269,41338,41340,41342,87668,41344,41346,41348,55614,55616,87756,55618,54756,54758,55608,55610,55612,55594,55596,54766,54768,26830,4368,4369,31724,31726,82264,82272,32300,32410,82280,82286,32486,32488,70294,32464,32466,32468,32470,32472,47568,47570,47572,89258,47574,89262,47576,47578,89266,89270,75008,75010,75012,75014,75016,75018,75020,32454,32455" linkTravelTime="3.0,3.0,2.0,2.0,2.0,1.0,4.0,4.0,3.0,1.0,4.0,4.0,3.0,1.0,4.0,4.0,1.0,4.0,3.0,3.0,1.0,1.0,4.0,4.0,2.0,1.0,1.0,7.0,3.0,2.0,1.0,1.0,3.0,4.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,1.0,1.0,3.0,1.0,3.0,1.0,1.0,1.0,2.0,6.0,1.0,1.0,1.0,1.0,4.0,4.0,1.0,1.0,1.0,1.0,3.0,2.0,2.0,3.0,3.0,3.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,2.0,1.0,1.0,1.0,7.0,1.0,1.0,3.0,4.0,3.0,10.0,2.0,3.0,4.0,2.0,3.0,2.0,1.0,3.0,1.0,4.0,1.0,5.0,5.0,3.0,3.0,4.0,4.0,1.0,2.0,3.0,3.0,1.0,5.0,2.0,3.0,1.0,1.0,1.0,3.0,4.0,4.0,1.0,3.0,1.0,1.0,4.0,2.0,2.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,3.0,4.0,4.0,1.0,1.0,3.0,1.0,4.0,4.0,1.0,1.0,4.0,1.0,1.0,4.0,4.0,4.0,1.0,1.0,1.0,1.0,2.0,7.0,1.0,8.0,1.0,7.0,1.0,8.0,1.0,2.0,1.0,3.0,4.0,3.0,2.0,4.0,4.0,4.0,1.0,1.0,4.0,4.0,1.0,3.0,1.0,19.0,2.0,5.0,9.0,4.0,15.0,4.0,1.0,1.0" primaryFuelType="Gasoline" secondaryFuelType="None" primaryFuel="3.5527917924899966E7" secondaryFuel="0.0" capacity="4" startX="-122.3970085" startY="37.7664337" endX="-122.4857432" endY="37.7482262" primaryFuelLevel="3.58450953580242E9" secondaryFuelLevel="0.0" seatingCapacity="4" tollPaid="0.0"  />
> ```
> 
> The warnings comes from the line [CarRideStatsFromPathTraversalEventHandler.scala#L352](https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/analysis/cartraveltime/CarRideStatsFromPathTraversalEventHandler.scala#L352)

Fixed issue for cavs

**Comment by SHaaD94** [comment]
Thank you, @REASY. 
I fixed issue for CAVs.

**Comment by REASY** [comment]
@SHaaD94 it has failed for sf-light-10k on my side:
```
14:08:29.903 ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
java.util.NoSuchElementException: key not found: beam.analysis.cartraveltime.Personal$@106387cf
	at scala.collection.MapLike.default(MapLike.scala:235)
	at scala.collection.MapLike.default$(MapLike.scala:234)
	at scala.collection.AbstractMap.default(Map.scala:63)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:63)
	at beam.analysis.cartraveltime.CarRideStatsFromPathTraversalEventHandler.notifyIterationEnds(CarRideStatsFromPathTraversalEventHandler.scala:140)
	at beam.sim.BeamSim.notifyIterationEnds(BeamSim.scala:225)
	at org.matsim.core.controler.ControlerListenerManagerImpl.fireControlerIterationEndsEvent(ControlerListenerManagerImpl.java:168)
	at org.matsim.core.controler.AbstractController$5.run(AbstractController.java:161)
	at org.matsim.core.controler.AbstractController.iterationStep(AbstractController.java:224)
	at org.matsim.core.controler.AbstractController.iteration(AbstractController.java:157)
	at org.matsim.core.controler.AbstractController.doIterations(AbstractController.java:114)
	at org.matsim.core.controler.AbstractController.access$000(AbstractController.java:28)
	at org.matsim.core.controler.AbstractController$1.run(AbstractController.java:84)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:48)
	at org.matsim.core.controler.MatsimRuntimeModifications.run(MatsimRuntimeModifications.java:31)
	at org.matsim.core.controler.AbstractController.run(AbstractController.java:92)
	at org.matsim.core.controler.NewControler.run(NewControler.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy20.run(Unknown Source)
	at beam.sim.BeamHelper.run(BeamHelper.scala:698)
	at beam.sim.BeamHelper.run$(BeamHelper.scala:697)
	at beam.sim.RunBeam$.run(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeam(BeamHelper.scala:573)
	at beam.sim.BeamHelper.runBeam$(BeamHelper.scala:551)
	at beam.sim.RunBeam$.runBeam(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamWithConfig(BeamHelper.scala:496)
	at beam.sim.BeamHelper.runBeamWithConfig$(BeamHelper.scala:461)
	at beam.sim.RunBeam$.runBeamWithConfig(RunBeam.scala:5)
	at beam.sim.BeamHelper.runBeamUsing(BeamHelper.scala:325)
	at beam.sim.BeamHelper.runBeamUsing$(BeamHelper.scala:319)
	at beam.sim.RunBeam$.runBeamUsing(RunBeam.scala:5)
	at beam.sim.RunBeam$.main(RunBeam.scala:14)
	at beam.sim.RunBeam.main(RunBeam.scala)
```

**Comment by REASY** [comment]
test!

**Pull request merged**
