### PR TITLE
Scenario template

### LINKED ISSUE #3692: Scenario template
We have a minimum set of files required to run beam - a scenario which is good to be used as a template for new city scenarios.
It is located in `test/input/scenario-template`

It is required some improvements:
1. we need to be able to run beam without vehicles.csv file if it is not provided (if it is possible - this file should be removed from the template)
2. we need to be able to run beam without toll-prices file if it is not provided (if it is possible - the file should be removed from the template)
3. add a page into internal wiki with a small description of scenario-template. as a sub-section of generation of new scenario
4. mention in the wiki that there is a `benchmark.csv` file and this file is used to add a column into reference modeChoice diagram

### PR DESCRIPTION
**Pull request by HoneyTauOverTwo**
Changes made to accommodate #3692 items 1. and 2.

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3700)

### CODE REVIEW

**Comment by HoneyTauOverTwo** [comment]
A diff between the folders output from scenario-template before and after commit b9db57e shows that they are virtually the same.

Comparing the output to beamville scenario, it contains almost the same files, beamville contains additional files related to modes not present in scenario-template (like mixed mode).

Also, changing intercepts values does impact the modes distribution accordingly.

**Comment by HoneyTauOverTwo** [comment]
Changing tool-prices.csv to: (which will result in $0 tools everywhere instead of $1)

linkId,toll,timeRange
1,0,[:]
150,0,[3000:]
200,0,[:]
228,0,[:]
And comparing the mode choice before and after commit 7ab9bab shows that it is unaffected. Meaning that omitting toll-prices.csv behaves as if there were no tolls.

The previous behavior was different, if there was no beam.agentsim.toll.filePath provided, [/test/input/beamville/toll-prices.csv](https://media.githubusercontent.com/media/LBNL-UCB-STI/beam/develop/test/input/beamville/toll-prices.csv) would be used, which reflects in a $1 toll for links 1, 150, 200 and 228.

**Comment by HoneyTauOverTwo** [comment]
test!

**Comment by HoneyTauOverTwo** [comment]
test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by HoneyTauOverTwo** [comment]
test!

**Pull request merged**
