### PR TITLE
zn/#3138 parking event on init

### LINKED ISSUE #3138: Throw ParkingEvent when vehicle is initialized into a parking stall
ParkingEvents are thrown by DrivesVehicle, but parking also happens at the beginning of the simulation. As of now, we can't see in the events file where vehicles are initialized. Would it be possible to have these events thrown when vehicles are initialized as well? Perhaps here: https://github.com/LBNL-UCB-STI/beam/blob/77188232e7572a75fce823451077194acde61d73/src/main/scala/beam/agentsim/agents/household/HouseholdFleetManager.scala#L51

### PR DESCRIPTION
**Pull request by zneedell**
Puts initial parking locations in the events file and makes sure that a vehicle's initial location matches its initial parking stall rather than the household location (because initial parking stalls might not be located exactly at home).

Resolves #3138

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3139)

### CODE REVIEW

**Comment by zneedell** [comment]
Still need to fix parking test

**Comment by JustinPihony** [comment]
In case the CI expires again:

> 23:28:07 PersonWithPersonalVehiclePlanSpec:
> 23:28:07 A PersonAgent
> 23:28:07 - should know how to take a car trip when it's already in its plan *** FAILED *** (351 milliseconds)
> 23:28:07   java.lang.AssertionError: assertion failed: expected class beam.router.BeamRouter$EmbodyWithCurrentTravelTime, found class beam.agentsim.events.ParkingEvent (	<event time="0.0" type="ParkingEvent" vehicle="car-dummyAgent" driver="None" cost="0.0" locationX="0.010023960668250636" locationY="0.010091999277618294" parkingType="Public" pricingModel="None" chargingType="None" parkingTaz="default"  />)
> 23:28:07   at scala.Predef$.assert(Predef.scala:223)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:570)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:541)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:540)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.expectMsgType(PersonWithPersonalVehiclePlanSpec.scala:41)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.$anonfun$new$2(PersonWithPersonalVehiclePlanSpec.scala:146)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 23:28:07   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 23:28:07   at org.scalatest.Transformer.apply(Transformer.scala:22)
> 23:28:07   ...
> 23:28:07 - should know how to take a bicycle trip when it's already in its plan *** FAILED *** (414 milliseconds)
> 23:28:07   java.lang.AssertionError: assertion failed: expected class beam.agentsim.events.ModeChoiceEvent, found class beam.agentsim.events.ParkingEvent (	<event time="0.0" type="ParkingEvent" vehicle="bicycle-dummyAgent" driver="None" cost="0.0" locationX="-1.4887438847070604" locationY="0.0" parkingType="Public" pricingModel="None" chargingType="None" parkingTaz="default"  />)
> 23:28:07   at scala.Predef$.assert(Predef.scala:223)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:570)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:541)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:540)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.expectMsgType(PersonWithPersonalVehiclePlanSpec.scala:41)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.$anonfun$new$9(PersonWithPersonalVehiclePlanSpec.scala:410)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 23:28:07   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 23:28:07   at org.scalatest.Transformer.apply(Transformer.scala:22)
> 23:28:07   ...
> 23:28:07 - should use another car when the car that is in the plan is taken *** FAILED *** (467 milliseconds)
> 23:28:07   java.lang.AssertionError: assertion failed: expected:  but got unexpected message CompletionNotice(0,Vector())
> 23:28:07   at scala.Predef$.assert(Predef.scala:223)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:478)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:474)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.expectMsgPF(PersonWithPersonalVehiclePlanSpec.scala:41)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.$anonfun$new$18(PersonWithPersonalVehiclePlanSpec.scala:529)
> 23:28:07   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.$anonfun$new$14(PersonWithPersonalVehiclePlanSpec.scala:528)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 23:28:07   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 23:28:07   ...
> 23:28:07 - should walk to a car that is far away (if told so by the router *** FAILED *** (397 milliseconds)
> 23:28:07   java.lang.AssertionError: assertion failed: expected class beam.router.BeamRouter$RoutingRequest, found class beam.router.BeamRouter$EmbodyWithCurrentTravelTime (EmbodyWithCurrentTravelTime(BeamLeg(CAR @ 28800,dur:1,path: 228 .. 108),car-2,beamVilleCar,5407))
> 23:28:07   at scala.Predef$.assert(Predef.scala:223)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:570)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:541)
> 23:28:07   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:540)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.expectMsgType(PersonWithPersonalVehiclePlanSpec.scala:41)
> 23:28:07   at beam.agentsim.agents.PersonWithPersonalVehiclePlanSpec.$anonfun$new$19(PersonWithPersonalVehiclePlanSpec.scala:630)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 23:28:07   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 23:28:07   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 23:28:07   at org.scalatest.Transformer.apply(Transformer.scala:22)
> 
> 23:28:07 ParkingSpec:
> 23:28:07 Parking system
> 23:28:07 - must departure and arrival should be from same parking 4 tuple *** FAILED *** (16 milliseconds)
> 23:28:07   java.lang.UnsupportedOperationException: empty.tail
> 23:28:07   at scala.collection.TraversableLike.tail(TraversableLike.scala:556)
> 23:28:07   at scala.collection.TraversableLike.tail$(TraversableLike.scala:555)
> 23:28:07   at scala.collection.mutable.ArrayBuffer.scala$collection$IndexedSeqOptimized$$super$tail(ArrayBuffer.scala:49)
> 23:28:07   at scala.collection.IndexedSeqOptimized.tail(IndexedSeqOptimized.scala:132)
> 23:28:07   at scala.collection.IndexedSeqOptimized.tail$(IndexedSeqOptimized.scala:132)
> 23:28:07   at scala.collection.mutable.ArrayBuffer.tail(ArrayBuffer.scala:49)
> 23:28:07   at beam.integration.ParkingSpec.$anonfun$new$8(ParkingSpec.scala:148)
> 23:28:07   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
> 23:28:07   at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:394)
> 23:28:07   at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:721)
> 23:28:07   ...
> 23:28:07 - must Park event should be thrown after last path traversal *** FAILED *** (106 milliseconds)
> 23:28:07   0 was not greater than 1 (ParkingSpec.scala:205)

**Review by JustinPihony — APPROVED** [review]
Once tests are fixed lgtm

**Comment by haitamlaarabi** [comment]
Test now!

**Review by haitamlaarabi — APPROVED** [review]
Looks okay

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3139#-:-NE3Q7csARScaubGrSdr:bsrklid)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zneedell)

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Pull request merged**
