### PR TITLE
ma/#1028-update-default-config-for-iter-linkstats-output-4ci Updated …

### LINKED ISSUE #1028: is iter.linkstats.txt used anywhere, e.g. for warmstart?
if not , don't write it out anymore

### PR DESCRIPTION
**Pull request by mr-asif-nor**
Fixed #1028
…the linkstats module config to disable it effectively for writing linkstats.txt.gz file

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1055)

### CODE REVIEW

**Comment by mr-asif-nor** [comment]
Its a matsim module config. Perhaps this is the right way to do this. I had a discussion on this with @wrashid He can better confirm.

**Comment by colinsheppard** [comment]
@mr-asif-nor please see what we're doing in this PR for an example of how we want this:

https://github.com/LBNL-UCB-STI/beam/pull/1061

You could wait for that PR to be merged and then follow the example there.

**Comment by mr-asif-nor** [comment]
Ok

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Pull request merged**
