### PR TITLE
Truck volume in linkstats

### LINKED ISSUE #3499: Truck volumes in linkstats
@haitamlaarabi:
All vehicles that are flagged as LightDutyTruck and HeavyDutyTruck would appear in the linkstats under truckVolume, while keeping all vehicles (including trucks) in default volume.

also I think I would even push it further and add another column for High Duty Truck Volume.
This will help with validating and calibrating BEAM.
So in short, Volume, TruckVolume, HDTruckVolume
Volume = CarVolume + Low Duty Truck Volume + High Duty Truck Volume
TruckVolume = Low Duty Truck Volume + High Duty Truck Volume
HDTruckVolume = High Duty Truck Volume

### PR DESCRIPTION
**Pull request by dimaopen**
Fixed not available truck vehicles
Added truck volumes to linkstats
A new test case is going to be added to this PR or to a new one

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3500)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by JustinPihony** [comment]
@dimaopen This seems to be a subset of https://github.com/LBNL-UCB-STI/beam/pull/3514 - which one should supersede and/or merge first?

**Pull request merged**
