### PR TITLE
Issue-3487 Populate riders for PathTraversal events for Bike and Walk modes

### PR DESCRIPTION
**Pull request by g-derzhavets**
[Issue-3487 ](https://github.com/LBNL-UCB-STI/beam/issues/3487) populate riders for bike and walk modes for PathTraversal events

For bike/walk modes a person ID is set as riders value.

image

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3490)

### CODE REVIEW

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by Xuan-1998** [comment]
1

**Review by Xuan-1998 — APPROVED** [review]
LGTM

**Pull request merged**
