### PR TITLE

Allow to do a mode choice if the current mode cannot be implemented

### LINKED ISSUE #3462: Allow to do a mode choice if the current mode cannot be implemented
@zneedell: When someone has “**CAR**” as their tour mode and they’re in `choosingMode`, and they get the set of vehicles available from the fleet managers and they don’t have access to any cars, they go straight to a **WALK** trip. Would it make sense to instead send them back to mode choice so they have the option of choosing another mode? There might be some other situations in mode choice where we give up and force a **WALK** trip when it would make more sense to go back to choosing mode as well

### PR DESCRIPTION
**Pull request by dimaopen**
If there's no alternative to do a mode choice the process of mode choice starts again (without predefinded tour mode).

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3463)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by zneedell — APPROVED** [review]
Lgtm

**Comment by zneedell** [comment]
I would be curious to confirm whether this leads to any big changes in a production run

**Comment by dimaopen** [comment]
> I would be curious to confirm whether this leads to any big changes in a production run

I think that some changes would be but not too big

**Pull request merged**
