### PR TITLE
Removed 20 warnings

### PR DESCRIPTION
**Pull request by carloscaldas**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2651)

### CODE REVIEW

**Comment by JustinPihony** [comment]
Test!

**Comment by JustinPihony** [comment]
For posterity - my guess is that the file utility is closing a resource prematurely:

> RideHailAllocationRandomRepositioningSpec:
> 23:07:10 - should be able to run for 1 iteration without exceptions *** FAILED *** (1 second, 624 milliseconds)
> 23:07:10   com.google.inject.CreationException: Unable to create injector, see the following errors:

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
Test!

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
test!

**Pull request merged**
