### PR TITLE
Fixing HierarchicalParkingManager after the parking zone id was introduced

### PR DESCRIPTION
**Pull request by dimaopen**
HierarchicalParkingManager couldn't work in the right way if we introduce a real parking zone id. This PR is intended to fix it.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)

### CODE REVIEW

**Review by haitamlaarabi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: all files reviewed, 1 unresolved discussion (waiting on @dimaopen)

___
*[src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala, line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-MzxOg0B3du-Y1CfNWDx:b-5k7toi) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
> ```Scala
>         }
>       )
>       val link = zone.link.getOrElse(MathUtils.selectRandomElement(links, random))
> ```

I still don't see where plugs are uniquely identified . Does select random element supposed to be for links only ? Or is there a different process for plugs with coordinates?

**Review by dimaopen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: all files reviewed, 1 unresolved discussion (waiting on @haitamlaarabi)

___
*[src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala, line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N-gICXcBH86-6PPmuf_:bjlewk5) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

I still don't see where plugs are uniquely identified . Does select random element supposed to be for links only ? Or is there a different process for plugs with coordinates?
</blockquote></details>

It's an utility method that is not related to searching plugs. It generates a link parking file out of TAZ parking. It is required mainly for testing. But if the taz parking contains coordinates (generally it defines the link) then the corresponding link is taken. In this case we can use this method to generate a production ready link parking file.

If you interested in looking how the plug is searched then you can see that we start searching a plug (parking zone) on the TAZ level, and if found search for the closest plug (parking zone) within that TAZ. It's the line where we creates the parking stall for the link parkin zone (copying the `parkingZoneId`)

https://github.com/LBNL-UCB-STI/beam/blob/b6efe1af95bd733f2d48ac1911cf21eac2938816/src/main/scala/beam/agentsim/infrastructure/HierarchicalParkingManager.scala#L166

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by haitamlaarabi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: 17 of 20 files reviewed, 1 unresolved discussion (waiting on @dimaopen and @haitamlaarabi)

___
*[src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala, line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N0C1MYy4R_j08HT1-9D:b-hm5bjz) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, dimaopen (Dmitrii Openkov) wrote…</i></summary><blockquote>

It's an utility method that is not related to searching plugs. It generates a link parking file out of TAZ parking. It is required mainly for testing. But if the taz parking contains coordinates (generally it defines the link) then the corresponding link is taken. In this case we can use this method to generate a production ready link parking file.

If you interested in looking how the plug is searched then you can see that we start searching a plug (parking zone) on the TAZ level, and if found search for the closest plug (parking zone) within that TAZ. It's the line where we creates the parking stall for the link parkin zone (copying the `parkingZoneId`)

https://github.com/LBNL-UCB-STI/beam/blob/b6efe1af95bd733f2d48ac1911cf21eac2938816/src/main/scala/beam/agentsim/infrastructure/HierarchicalParkingManager.scala#L166
</blockquote></details>

Understood.
Can we adjust the parking reading file in a way that when it reads a parking file with coordinates, it assigns them to Links, and then aggregate those parking file based on:

"taz,parkingType,chargingPointType,pricingModel,feeInCents,reservedFor"

while numStalls is calculated by summing all num stalls under the tuple above,
and parkingZoneId is first parkingZoneId in the tuple above, or generate one with existing method if parkingZoneId is empty.

**Review by dimaopen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: 17 of 20 files reviewed, 1 unresolved discussion (waiting on @dimaopen and @haitamlaarabi)

___
*[`src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala` line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N0eM2U89UpSv2ydHKAQ:bh7f3ac) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Understood.
Can we adjust the parking reading file in a way that when it reads a parking file with coordinates, it assigns them to Links, and then aggregate those parking file based on:

"taz,parkingType,chargingPointType,pricingModel,feeInCents,reservedFor"

while numStalls is calculated by summing all num stalls under the tuple above,
and parkingZoneId is first parkingZoneId in the tuple above, or generate one with existing method if parkingZoneId is empty.
</blockquote></details>

But in this case we couldn't analyze or parking zones on individual levels. Their parking ids is going to be lost.

**Review by haitamlaarabi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: 18 of 20 files reviewed, 2 unresolved discussions (waiting on @dimaopen)

___
*[`src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala` line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N1G_bH8D_2QJ7voksGB:bfutrau) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, dimaopen (Dmitrii Openkov) wrote…</i></summary><blockquote>

But in this case we couldn't analyze or parking zones on individual levels. Their parking ids is going to be lost.
</blockquote></details>

that's true. ideally we want to keep the Parking Ids. Where did you store the parking Ids and how do you look them up?
___
*[`src/main/scala/beam/agentsim/infrastructure/parking/TazToLinkLevelParkingApp.scala` line 66 at r2](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-N1GaGdU1F2T9iZBjfvT:-N1GaGdU1F2T9iZBjfvU:b-93nu9t) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/cb1df776ac957e186589cb0a57bc91f4039cf352/src/main/scala/beam/agentsim/infrastructure/parking/TazToLinkLevelParkingApp.scala#L66)):*
> ```Scala
>   }
> 
>   val zoneArrayLink: Map[Id[ParkingZoneId], ParkingZone[Link]] = zonesLink
> ```

Is this where you store the IDs. Did you remove it. If that's the case, let's roll back the changes and keep the IDs if it doesn't make runtime much slower!

**Review by dimaopen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: 1 of 58 files reviewed, 2 unresolved discussions (waiting on @dimaopen and @haitamlaarabi)

___
*[`src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala` line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N1I_5-x4O1PjZ0vbTnh:bp5kjbs) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

that's true. ideally we want to keep the Parking Ids. Where did you store the parking Ids and how do you look them up?
</blockquote></details>

Parking Ids are keept in their place: in the `parkingZone` class.
Hierarcial Manager searches for a parking zone at the TAZ level first. At this level we generate TAZ parking zones including their Ids. The ids don't matter at this level.
When an appropriate parking zone is found on the TAZ level we search for a parking zone within that TAZ. And the real parking zones (with their real ids) are looked through here. When a zone found it is provided to the client with its real id.

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by haitamlaarabi — APPROVED** [review]
> Reviewed 57 of 57 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: all files reviewed, 1 unresolved discussion (waiting on @dimaopen)

___
*[`src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala` line 620 at r1](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-MzxOg0B3du-Y1CfNWDw:-N1LukhKEmoiZlq_zMx5:b-87hbi0) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/977f902c17847c849ed46300c3acd89a45378467/src/main/scala/beam/agentsim/infrastructure/parking/ParkingZoneFileUtils.scala#L620)):*
<details><summary><i>Previously, dimaopen (Dmitrii Openkov) wrote…</i></summary><blockquote>

Parking Ids are keept in their place: in the `parkingZone` class.
Hierarcial Manager searches for a parking zone at the TAZ level first. At this level we generate TAZ parking zones including their Ids. The ids don't matter at this level.
When an appropriate parking zone is found on the TAZ level we search for a parking zone within that TAZ. And the real parking zones (with their real ids) are looked through here. When a zone found it is provided to the client with its real id.
</blockquote></details>

Great

**Comment by haitamlaarabi** [comment]
Test now!

**Review by dimaopen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506)* status: all files reviewed, 1 unresolved discussion (waiting on @haitamlaarabi)

___
*[`src/main/scala/beam/agentsim/infrastructure/parking/TazToLinkLevelParkingApp.scala` line 66 at r2](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3506#-N1GaGdU1F2T9iZBjfvT:-N1NAxztCphNuHnfSnKp:bsaw0a3) ([raw file](https://github.com/lbnl-ucb-sti/beam/blob/cb1df776ac957e186589cb0a57bc91f4039cf352/src/main/scala/beam/agentsim/infrastructure/parking/TazToLinkLevelParkingApp.scala#L66)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Is this where you store the IDs. Did you remove it. If that's the case, let's roll back the changes and keep the IDs if it doesn't make runtime much slower!
</blockquote></details>

No, this file is just a helper utility that generally needs for testing. It converts TAZ parking to link parking. But it just randomly assign links from a particular TAZ to zones.

**Pull request merged**
