### PR TITLE
Hl/#1857 test vehiclesharing repositioning

### PR DESCRIPTION
**Pull request by htmlrb**
new parameters, bug Fix, Test Ok, merge Ok

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1865)

### CODE REVIEW

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
Test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
Test!

**Comment by htmlrb** [comment]
Test!

**Comment by htmlrb** [comment]
test!

**Comment by michaz** [comment]
test!

**Pull request merged**
