### PR TITLE
Ma/#371 cacc jdeqsim 4ci

### PR DESCRIPTION
**Pull request by mr-asif-nor**
Implemented the cacc map for JDEQSimulation

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1258)

### CODE REVIEW

**Comment by mr-asif-nor** [comment]
test!

**Comment by mr-asif-nor** [comment]
test!

**Comment by mr-asif-nor** [comment]
test!

**Comment by wrashid** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Pull request merged**
