### PR TITLE
update cost burden by dest act type

### PR DESCRIPTION
**Pull request by wrashid**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1810)

### CODE REVIEW

**Comment by wrashid** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Comment by wrashid** [comment]
@rajnikantsh please update PersonCostAnalysisSpec to accommodate for the change

**Comment by rajnikantsh** [comment]
Test!

**Comment by rajnikantsh** [comment]
Test!

**Comment by rajnikantsh** [comment]
Test!

**Comment by rajnikantsh** [comment]
Test!

**Pull request merged**
