### PR TITLE
Bl/#2296 network io fixes for mep 4ci

### PR DESCRIPTION
**Pull request by bhavyalatha26**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2300)

### CODE REVIEW

**Comment by bhavyalatha26** [comment]
> This does not fully resolve #2296, correct?

yes @JustinPihony

**Comment by zneedell** [comment]
Test!

**Comment by wrashid** [comment]
Test now

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test now!

**Pull request merged**
