### PR TITLE
AWS: Save current git branch commit and git data branch commit into spreadsheet

### LINKED ISSUE #3449: AWS: Save current git branch commit and git data branch commit into spreadsheet
In order to be able to reproduce past simulations we might need to save into spreadsheet the real git branch commit (in case a simulation was started without specifying a commit hash) and git data branch commit.

An example of simulations started without specifying a commit hash
image

### PR DESCRIPTION
**Pull request by alex-vv**
Fixes #3449

I added the existing lambda function `spreadsheetData` to the repository, migrating credentials loading from lambda environment variables

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3543)

### CODE REVIEW

**Comment by alex-vv** [comment]
test!

**Comment by alex-vv** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by alex-vv** [comment]
test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
