### PR TITLE
Enable max number of modes to be produced in BackgroundSkimsCreatorApp

### PR DESCRIPTION
**Pull request by dimaopen**
I measured the number of different trip types that are returned from the router and found that if both WALK and CAR enabled and withTransit enabled then WALK_TRANSIT and DRIVE_TRANSIT numbers are roughly equal to single CAR or WALK enalbed.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3250)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]
I am little bit concerned by the fact we won't be able to build only drive transit skims without building walk transit skims if we use feature to generate full skims during beam simulation.
But it seems we are not going to use this feature at all since we are going to generate skims by app.

**Comment by alex-vv** [comment]
LGTM

**Review by alex-vv — APPROVED** [review]

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Pull request merged**
