### PR TITLE
Add or-tools

### PR DESCRIPTION
**Pull request by SHaaD94**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2377)

https://github.com/LBNL-UCB-STI/or-tools-wrapper

### CODE REVIEW

**Comment by REASY** [comment]
I can see some failed tests, https://beam-ci.tk/job/beam-4ci/7541/consoleFull:
```
java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
00:14:18   at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
00:14:18   at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
00:14:18   at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
00:14:18   at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
00:14:18   at org.mapdb.DBMaker.make(DBMaker.java:701)
00:14:18   at com.conveyal.osmlib.OSM.<init>(OSM.java:106)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:198)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:178)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:306)
00:14:18   at beam.router.r5.NetworkCoordinator.loadNetwork(NetworkCoordinator.scala:77)
00:14:18   ...
00:14:18   Cause: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
00:14:18   at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
00:14:18   at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
00:14:18   at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
00:14:18   at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
00:14:18   at org.mapdb.DBMaker.make(DBMaker.java:701)
00:14:18   at com.conveyal.osmlib.OSM.<init>(OSM.java:106)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:198)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:178)
00:14:18   at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:306)
00:14:18   at beam.router.r5.NetworkCoordinator.loadNetwork(NetworkCoordinator.scala:77)
```

**Comment by REASY** [comment]
test!

**Comment by SHaaD94** [comment]
test!

**Comment by SHaaD94** [comment]
test!

**Comment by haitamlaarabi** [comment]
On Mac, i'm getting:
`Exception in thread "main" java.lang.VerifyError: class org.openstreetmap.osmosis.osmbinary.Fileformat$BlobHeader overrides final method getParserForType.()Lcom/google/protobuf/Parser;
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.openstreetmap.osmosis.osmbinary.file.FileBlockHead.readHead(FileBlockHead.java:56)
	at org.openstreetmap.osmosis.osmbinary.file.FileBlock.process(FileBlock.java:130)
	at org.openstreetmap.osmosis.osmbinary.file.BlockInputStream.process(BlockInputStream.java:34)
	at com.conveyal.osmlib.PBFInput.copyTo(PBFInput.java:237)
	at com.conveyal.osmlib.OSM.readFromFile(OSM.java:202)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:200)
	at com.conveyal.r5.transit.TransportNetwork.fromFiles(TransportNetwork.java:178)
	at com.conveyal.r5.transit.TransportNetwork.fromDirectory(TransportNetwork.java:306)
	at beam.router.r5.NetworkCoordinator.loadNetwork(NetworkCoordinator.scala:77)
	at beam.router.r5.NetworkCoordinator.loadNetwork$(NetworkCoordinator.scala:56)`

this is probably due to protobuf-java, coming with or-tools. What about adding a gradle exception that excludes that jar from loading!?

**Comment by SHaaD94** [comment]
> Is this PR ready for review? I only see it loading and not doing anything with it right now. Also, is there a reason for using com.github? It's not a huge jump to figure out at this early stage that it is something in our control, but later it could pose more of a challenge for newcomers to understand that this is an lbnl tool - not GitHub.

This PR is for replace existing 3rd party library for OR-Tools, it is being used in AlonsoMora pooling algorithm.
About com.github - we can rename it, just tell me preferred library package name.

**Comment by JustinPihony** [comment]
@wrashid @colinsheppard Any preference? Since it is for beam I'd say we stick with the beam namespace: `beam.utilities.ortoolwrapper`? And then it begs the question if this needs to be its own dependency or if it is small enough to be part of utilities itself?

**Comment by SHaaD94** [comment]
test!

**Comment by SHaaD94** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
Actual exception somehow is not visible. Here is what I see:
```
*** RUN ABORTED ***
  java.lang.VerifyError: class org.openstreetmap.osmosis.osmbinary.Fileformat$BlobHeader overrides final method getParserForType.()Lcom/google/protobuf/Parser;
  at java.lang.ClassLoader.defineClass1(Native Method)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
  at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
  at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
  at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
  at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  ...


FAILURE: Build failed with an exception.
```

**Comment by haitamlaarabi** [comment]
It is still failing. the exclude doesn't work as protobuf is encapsulated inside the wrapper jar.
Screen Shot 2020-03-02 at 3 41 01 PM

**Comment by REASY** [comment]
@JustinPihony I think it fine that we leave the name as is. For example, beam-utilities has the following naming:
```
group: 'com.github.LBNL-UCB-STI', name: 'beam-utilities', version: 'v0.2.4'
```

**Pull request merged**
