### PR TITLE
Fdariasm/integration revert

### PR DESCRIPTION
**Pull request by fdariasm**
Reverting missing changes for EventsFileSpec, un-ignoring two passing tests. Please check and confirm to merge back to master.

### CODE REVIEW

**Comment by michaz** [comment]
Thanks -- actually, I was happy to get rid of the ``getListOfSubDirectories`` thing in ``EventsFileHandlingCommon``, but now it's coming back.. The real output directory is contained in  ``matsimConfig.controler().getOutputDirectory``, so it doesn't need to be guessed but can be taken from there, like in ``getEventsFilePath``, just above ``getRouteFile``. Can it be done the same way in your case?

**Comment by fdariasm** [comment]
Yes for sure, I missed that change.

**Comment by fdariasm** [comment]
@michaz done, sorry for the delay, I was having lunch

**Comment by michaz** [comment]
Okay, thanks!

**Pull request merged**
