### PR TITLE
Add more logging

### PR DESCRIPTION
**Pull request by JustinPihony**
This seems simple at it's root - however I want to double check that my GC thoughts are in line - that this will only be a big issue if set to debug or info. Otherwise it's merely adding logging

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2329)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
