### PR TITLE
Add bike_transit

### LINKED ISSUE #1915: implement bike_transit mode

### PR DESCRIPTION
**Pull request by rajnikantsh**
Fixes #1915 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1918)

### CODE REVIEW

**Comment by REASY** [comment]
Should be there any changes to these places:
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/modalbehaviors/ModeChoiceCalculator.scala#L67
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/router/BeamSkimmer.scala#L101
https://github.com/LBNL-UCB-STI/beam/blob/develop/src/main/scala/beam/agentsim/agents/choice/mode/ModeChoiceMultinomialLogit.scala#L147

**Comment by rajnikantsh** [comment]
Hi @REASY , Apart from your mentioned location i have added BIKE_TRANSIT on other locations. Please have a look into this.

**Comment by JustinPihony** [comment]
@wrashid @colinsheppard Can this be merged (minus the conflict)?

**Comment by rajnikantsh** [comment]
test!

**Comment by rajnikantsh** [comment]
test!

**Comment by michaz** [comment]
Hmm, what does the test test? It doesn't seem to test if anybody is using `bike_transit` at all...

**Pull request merged**
