### PR TITLE
Fdariasm/#600 fix broken tests 4ci

### LINKED ISSUE #600: Fix broken tests related to vehicle types refactor
The following were ignored in order to complete pull #595, should be fixed:

ea215ae
5e4ef3e

### PR DESCRIPTION
**Pull request by fdariasm**
Fixed #600

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/676)

### CODE REVIEW

**Comment by fdariasm** [comment]
@colinsheppard two issues are failing, this is my report:
 - PersonTravelTimeStatsGraphSpec. Even though test is green, is giving an error: org.scalatest.exceptions.TestFailedException: Map("walk_transit" -> 1371.417, "ride_hail" -> 105.917, "walk" -> 22.65, "car" -> 14.683, "drive_transit" -> 519.883) did not equal Map("walk" -> 22.65, "ride_hail" -> 105.917, "drive_transit" -> 519.883, "others" -> 1494.6, "car" -> 14.683, "walk_transit" -> 1371.417)
Is failing because modes from EventsFile doesn't contain "others" category, which is a fabricated mode when computing the stats. Either compare without "others" or same logic when reading from events file.
Logic to count from eventsFile and create validation is in StatsValidationHandler.updateCounterTime.
Logic to count from simulation and create stats is in PersonTravelTimeAnalysis.processPersonArrivalEvent, line 185: otherMode.

- PersonTravelTimeTest: Test is using beamville/test-data/beamville.events.xml which doesn't contain any PersonDepartureEvent or PersonArrivalEvent, but the test logic requires them to work. Currently getting java.lang.ArrayIndexOutOfBoundsException: -1 when accessing an empty array. Test was commented out in master. A solution might be to update beamville.events.xml with one that does contain required events.

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Pull request closed without merging**
