### PR TITLE
Removes deprecated parameters from configurations.

### LINKED ISSUE #3117: Remove deprecated config parameters
Beam writes in the log the following:
```
**  
** Found the following deprecated parameters, you can safely remove them from your config file:
**  
**  beam.agentsim.agents.parking.mulitnomialLogit.params.distance_multiplier
**  beam.agentsim.agents.parking.mulitnomialLogit.params.installed_capacity_multiplier
**  beam.agentsim.agents.parking.mulitnomialLogit.params.parking_costs_price_multiplier
**  beam.agentsim.agents.rideHail.initialization.procedural.numDriversAsFractionOfPopulation
**  beam.outputs.generalizedLinkStats.interval
**  beam.outputs.writeSkimsInterval
```

Let us clean-up our configs. Also are those the only deprecated params?

### PR DESCRIPTION
**Pull request by HoneyTauOverTwo**
Running Beamville scenario currently now outputs more deprecated parameters (most of the originally reported are missing):

```
** Found the following deprecated parameters, you can safely remove them from your config file:
**  
**  beam.agentsim.agents.rideHail.refuelThresholdInMeters
**  beam.agentsim.startTime
**  beam.cosim.helics.federateName
**  beam.cosim.helics.timeStep
**  beam.outputs.writeLinkTraversalInterval
**  beam.physsim.writeMATSimNetwork
**  beam.replanning.cleanNonCarModesInIteration
**  beam.router.skim.collectFullCarSkimsInterval
**  beam.router.skim.h3Resolution
**  beam.router.skim.origin_destination_skimmer.fileBaseName
**  beam.router.skim.origin_destination_skimmer.name
**  beam.router.skim.origin_destination_skimmer.writeAllModeSkimsForPeakNonPeakPeriodsInterval
**  beam.router.skim.origin_destination_skimmer.writeFullSkimsInterval
**  beam.router.skim.travel-time-skimmer.fileBaseName
**  beam.router.skim.travel-time-skimmer.name
**  beam.routing.r5.osmFile
```

It has a duplicated parameter but with two different values, I am pretty sure the first one is being used, but they were left as is (should I remove the second?):

```
beam.outputs.baseOutputDirectory = ${PWD}"/output/sf-light"
beam.outputs.baseOutputDirectory = ${?BEAM_OUTPUT}
```

running beamville/beam-urbansimv2 did not output any other additional deprecated parameter. There were lots of duplicated parameters.

running network-relaxation-scenario did not output any other additional deprecated parameter.

running sf-light urbansim-1k scenario had the additional parameter as deprecated: ``beam.beamskimmer.writeObservedSkimsInterval``. Also, it had the following parameters duplicated:

```
**  beam.agentsim.agents.rideHail.surgePricing.minimumSurgeLevel
**  beam.agentsim.agents.rideHail.surgePricing.priceAdjustmentStrategy
**  beam.agentsim.agents.rideHail.surgePricing.surgeLevelAdaptionStep
```

sf-light urbansim-10k yielded the additional deprecated parameter: ``beam.outputs.writeSkimsInterval``

sf-light urbansim-250k yielded: ``beam.agentsim.agents.rideHail.initialization.procedural.numDriversAsFractionOfPopulation``

sf-light urbansim-100k yielded ``beam.agentsim.numAgents``.

Contrary to the previous scenarios, urbansim-10k, 100k and 250k, after being edited, were ran only until the simulation started, which I assume was enough to discard the possibility of configuration errors.

urbansim-25k failed with ``ERROR o.m.c.controler.AbstractController - Mobsim did not complete normally! afterMobsimListeners will be called anyway.`` even with the original config.

When trying to run the scenarios ``test/input/texas/austin...`` beam exits with errors due to missing files, for that reason I did not analyze those.

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3637)

### CODE REVIEW

**Comment by HoneyTauOverTwo** [comment]
Parameters removed:
```
beam.agentsim.startTime
beam.physsim.writeMATSimNetwork
beam.router.skim.h3Resolution
beam.replanning.cleanNonCarModesInIteration
beam.agentsim.agents.rideHail.refuelThresholdInMeters
beam.outputs.writeLinkTraversalInterval
beam.routing.r5.osmFile
beam.beamskimmer.writeObservedSkimsInterval
beam.outputs.writeSkimsInterval
beam.agentsim.agents.rideHail.initialization.procedural.numDriversAsFractionOfPopulation
beam.agentsim.numAgents
```

The parameter ``beam.routing.r5.osmFile`` used to be checked for consistency (https://github.com/LBNL-UCB-STI/beam/blob/9c4ee4d47f2b7803be5798cdb895779e16241879/src/main/scala/beam/utils/ConfigConsistencyComparator.scala#L183). The check was removed.

Parameters renamed:
```
beam.router.skim.travel-time-skimmer.{...} -> beam.router.skim.drive-time-skimmer.{...}
beam.router.skim.origin_destination_skimmer.{...} -> beam.router.skim.origin-destination-skimmer.{...}
beam.cosim.helics.{...} -> beam.agentsim.chargingNetworkManager.helics.{...}
beam.cosim.helics.timeStep [String] -> beam.agentsim.chargingNetworkManager.helics.timeDeltaProperty [Double]
```

**Comment by HoneyTauOverTwo** [comment]
There is still the need to modify the scenarios ``test/input/texas/austin...``. But beam exits with errors due to missing files, for that reason I did not analyze those.
I could remove the deprecated parameters identified so far (or even comparing them to beam-template.conf in search for more), but I would not have any way of testing them.

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
Let's fix the conflict by merging develop to this branch and run CI for the PR

**Comment by nikolayilyin** [comment]
Let's fix the conflict by merging develop to this branch and run CI for the PR

**Comment by HoneyTauOverTwo** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
