### PR TITLE
Using taz id instead of coordinates during payload plan conversion

### PR DESCRIPTION
**Pull request by dimaopen**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3247)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by haitamlaarabi** [comment]
Looks good!

**Review by haitamlaarabi — APPROVED** [review]
Looks good!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by haitamlaarabi** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
