### PR TITLE
replace append with prepend for lists

### PR DESCRIPTION
**Pull request by bhavyalatha26**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1538)

### CODE REVIEW

**Comment by REASY** [comment]
LGTM, but just to make sure it won't break any logic. Changing append to prepend will affect the order:
image
Am I right understand that it's fine for the caller/user of this change?

**Comment by bhavyalatha26** [comment]
> LGTM, but just to make sure it won't break any logic. Changing append to prepend will affect the order:
> image
> Am I right understand that it's fine for the caller/user of this change?

Yes @REASY its fine , as we calculate the sum/average of the values at the end , the order does not affect the use case here , so I made that change.

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
