### PR TITLE
1574 - Cleanup analysis (RealizedMode, ModeChosen)

### LINKED ISSUE #1574: Cleanup analysis (RealizedMode, ModeChosen)

### PR DESCRIPTION
**Pull request by borut123**
test!

fixes #1574 

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1578)

### CODE REVIEW

**Comment by wrashid** [comment]
Test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by wrashid** [comment]
Test!

**Pull request merged**
