### PR TITLE
add null pointer check for link value from getLinkUnsafe

### PR DESCRIPTION
**Pull request by bhavyalatha26**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1492)

### CODE REVIEW

**Comment by REASY** [comment]
I'm not sure this is right think to do. It has to fail as fast as it can, there are a lot of other places which uses `NetworkHelper`

**Comment by bhavyalatha26** [comment]
@REASY it is already failing with Null pointer exception , so had to ad this null check , do you suggest something else ?

**Comment by REASY** [comment]
@bhavyalatha26 do you have reproducible case, could you, please, show how to get NPE?

**Comment by bhavyalatha26** [comment]
@REASY its happening on production and was reported by @wrashid . 

PFA the screenshot he sent

image

**Comment by bhavyalatha26** [comment]
@rajnikantsh can you too add your views/comments here

**Comment by REASY** [comment]
@bhavyalatha26 I was one who got this exception. Basically I run sf-light which generated the network file. (it was two days ago). Today I run urban-sim and somehow it used old network file from sf-light

**Comment by REASY** [comment]
PR: https://github.com/LBNL-UCB-STI/beam/pull/1493 is going to fix this properly.

**Comment by zishanbilal** [comment]
!test

**Comment by zishanbilal** [comment]
test!

**Comment by wrashid** [comment]
solved by #1493

**Pull request closed without merging**
