### PR TITLE
#2613 - Derive maxSpeed and append it to OSM way node …

### LINKED ISSUE #2613: Derive the speed for the roads without speed data automatically
When there is no data about the speed for the link in OSM, we use [default speed per road type](https://github.com/LBNL-UCB-STI/beam-utilities/blob/master/src/main/java/beam/router/r5/OsmToMATSim.java#L155). Instead of having static default we could derive the speeds automatically. 
For all OSM roads which has both road type and speed tag:
1. Create a map from road type to the speeds for that road type
2. Compute median speed per road type
3. Use computed median speed for all roads which have no speed tag

### PR DESCRIPTION
**Pull request by jctim**
Closes #2613 
… for those who don't have

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3042)

### CODE REVIEW

**Comment by jctim** [comment]
Test!

**Comment by jctim** [comment]
Test!

**Comment by REASY** [comment]
@jctim could you wrap this functionality by the following config:
```
beam.physsim.network.maxSpeedInference {
  enabled = "boolean | false"
  # Possible types of inference: AVG, MEDIAN
  type = "string"
}
```
I see you already introduced AVG (Mean), could you also introduce Median?

**Comment by jctim** [comment]
@REASY sure

**Comment by jctim** [comment]
Run on sf-light.conf 
* for MEAN: 
```
INFO  beam.utils.osm.WayFixer$ - Derived maxSpeed in 14918 from 194795 using mapping:
Map(footway -> 48.28032, path -> 8.04672, primary_link -> 56.97947675675675, secondary_link -> 54.31536, pedestrian -> 24.14016, unclassified -> 34.043815384615385, secondary -> 49.34444790490342, service -> 21.21408, residential -> 38.72214356164383, trunk_link -> 52.30368, tertiary_link -> 52.66944, motorway_link -> 44.659296, cycleway -> 18.77568, motorway -> 82.57467428571428, tertiary -> 43.53616260586319, trunk -> 52.18962432, primary -> 50.10972257001647)
```
* for MEDIAN:
```
INFO  beam.utils.osm.WayFixer$ - Derived maxSpeed in 14918 from 194795 using mapping:
Map(footway -> 48.28032, path -> 8.04672, primary_link -> 56.32704, secondary_link -> 56.32704, pedestrian -> 24.14016, unclassified -> 32.18688, secondary -> 48.28032, service -> 24.14016, residential -> 40.2336, trunk_link -> 52.30368, tertiary_link -> 56.32704, motorway_link -> 32.18688, cycleway -> 24.14016, motorway -> 80.4672, tertiary -> 40.2336, trunk -> 48.28032, primary -> 48.28032)
```

**Comment by jctim** [comment]
Test!

**Comment by REASY** [comment]
test!

**Review by REASY — APPROVED** [review]

**Comment by REASY** [comment]
test now!

**Review by JustinPihony — APPROVED** [review]

**Pull request merged**
