### PR TITLE
merge new households too

### PR DESCRIPTION
**Pull request by zneedell**
Include new households in plan merging, downsampling them at the same rate as the original population

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3366)

### CODE REVIEW

**Comment by zneedell** [comment]
Test!

**Review by dimaopen — APPROVED** [review]
Approved with the notice I provided in Slack.

**Review by dimaopen — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3366)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zneedell)

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
