### PR TITLE
Bl/#1402 disabling write graph flag still generates graphs

### PR DESCRIPTION
**Pull request by bhavyalatha26**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1421)

### CODE REVIEW

**Comment by wrashid** [comment]
test!

**Comment by bhavyalatha26** [comment]
test!

**Comment by bhavyalatha26** [comment]
test!

**Comment by JustinPihony** [comment]
This looks like it just needs the conflict resolved and it can be merged unless I missed something :)

**Pull request closed without merging**
