### PR TITLE
A tool to get a shape file out of stops coordinates from GTFS archive

### PR DESCRIPTION
**Pull request by nikolayilyin**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2819)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
image
an example of all gtfs archives for NY scenario

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
image
stops grouped by agency

**Comment by nikolayilyin** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
