### PR TITLE
#3699 disable the way to run multiple simulations on the same instance

### PR DESCRIPTION
**Pull request by edwazhao**
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3715)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by edwazhao** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by edwazhao** [comment]
test!

**Comment by edwazhao** [comment]
test!

**Comment by edwazhao** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
