### PR TITLE
Cjrs/issue160 notransit

### PR DESCRIPTION
**Pull request by colinsheppard**
Issues #160 #150 are addressed here.

### CODE REVIEW

**Comment by colinsheppard** [comment]
@michaz can you please review and merge at your convenience?

Thanks!

**Comment by colinsheppard** [comment]
@michaz 

I mistakenly pushed some partial updates to master... I think once you review and merge this PR all will be well again:

https://travis-ci.org/LBNL-UCB-STI/beam/builds/311377071

**Comment by michaz** [comment]
Hmm, were the visualization commits developed on this branch, or did they get in here by accident? I'm just asking as a precaution, I don't want to produce merge conflicts later... Also the data file changes.

**Comment by michaz** [comment]
But since this is the de-facto master at the moment anyway, I guess I'll just merge. :-)

**Comment by colinsheppard** [comment]
That stuff made it's way in via application-sfbay which I've merged with my feature branch in order to test my bug fixes at scale. I'm not worried about them though because for now all viz stuff happens in post-processing and shouldn't impact the model itself.

**Comment by michaz** [comment]
What concerns me a bit is that this PR introduces a fix which patches data and messages with dummy values, but when I remove those changes (a2ad8c5), it still works.

Those lines look very much like we should have a test which shows what they are fixing, otherwise we won't understand after two weeks what we did there.

Since we have sfbay-light on master now, would it be possible to produce a test which fails now, in this state?

**Comment by michaz** [comment]
That would probably add "people use transit" to the sfbay-light spec.

I recently commented out the one spec on the result of that run, because Travis would choke on the event file. (Which is reasonable. We can't expect to load all events into _memory_, they are meant for stream processing.)

I'll try to put an example for testing event streams here.

**Pull request merged**
