### PR TITLE
Realized Mode: Freight

### PR DESCRIPTION
**Pull request by dimaopen**
Now it separates regular car mode and freight mode when generates realize mode csv and histograms.

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3694)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
LGTM

**Comment by nikolayilyin** [comment]
test!

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
