### PR TITLE
#3442/wheelchair accessible ridehail

### PR DESCRIPTION
**Pull request by zneedell**
Add a person attribute identifying whether an agent uses a wheelchair, and add a vehicle attribute identifying whether a vehicle is wheelchair accessible. When a wheelchair user requests a ridehail trip, only match them with ridehail accessible vehicles.

This is for some SMART scenario runs to be completed in January, not necessarily to be merged right away.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446)

### CODE REVIEW

**Comment by zneedell** [comment]
@haitamlaarabi Think you could take a look (no rush) and confirm this makes sense and that there aren't additional places where I need to apply this filter?

**Review by haitamlaarabi — APPROVED** [review]
> Reviewed 23 of 24 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zneedell)

**Review by haitamlaarabi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446)* status: all files reviewed, 1 unresolved discussion (waiting on @zneedell)

*[a discussion](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446#-MtqKI_FDa7iFKzKKaTF:-MtqKI_FDa7iFKzKKaTG:b-cmmkb9) (no related file):*
It looks neat. Although I didn't see a test function to make sure the functionality doesn't get downgraded overtime. 

---

**Comment by zneedell** [comment]
Still depends on merging the parking and ridehail skimmers

**Comment by haitamlaarabi** [comment]
Test now!

**Review by haitamlaarabi — APPROVED** [review]
Looks good

> Reviewed 15 of 35 files at r4, 4 of 19 files at r5, 21 of 21 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446#-:-NE3SszaBj9Naza3aLEX:bsrfkwe)* status: all files reviewed, 1 unresolved discussion (waiting on @zneedell)

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Review by haitamlaarabi — APPROVED** [review]
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3446)* status: all files reviewed, 1 unresolved discussion (waiting on @zneedell)

**Pull request merged**
