### PR TITLE
multiple secondary activities from home

### PR DESCRIPTION
**Pull request by zneedell**
Previously non-workers were limited to one secondary tour per day (it was one tour per mandatory activity). Added a fix allowing up to three secondary tours for non-workers. Could be generalized in the future.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2915)

### CODE REVIEW

**Comment by zneedell** [comment]
Test!

**Comment by nikolayilyin** [comment]
the problem is in flaky tests

**Comment by nikolayilyin** [comment]
test now!

**Review by nikolayilyin — APPROVED** [review]
LGTM

**Pull request merged**
