### PR TITLE
Fixed issue with casting a tuple to a skimmer key in ODSkimmer

### PR DESCRIPTION
**Pull request by dimaopen**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2956)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]

**Comment by nikolayilyin** [comment]
test now!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
test now!

**Pull request merged**
