### PR TITLE
Move all utilities into an upper level folder for easier discovery

### LINKED ISSUE #3445: Move all utilities into an upper level folder for easier discovery
Utilities that use `extends App` or defines `main(args: String[])` to be run standalone should probably be moved to an upper folder so they are all easily discovered

### PR DESCRIPTION
**Pull request by alex-vv**
fixes #3445

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3537)

### CODE REVIEW

**Review by dimaopen — COMMENTED** [review]
Generally it looks good. Though we have multiple files that moved without changes. I think that their package definition should be changed to the corresponding new folder.

**Comment by alex-vv** [comment]
> Generally it looks good. Though we have multiple files that moved without changes. I think that their package definition should be changed to the corresponding new folder.

thanks, pushed a fix

**Comment by alex-vv** [comment]
test!

**Review by dimaopen — COMMENTED** [review]
Utils like these `beam.utils.gtfs.GTFSToShape`, `beam.utils.RouteRequester` are not going to be moved to scripts?

**Comment by alex-vv** [comment]
> Utils like these beam.utils.gtfs.GTFSToShape, beam.utils.RouteRequester are not going to be moved to scripts?

yes, it looks I missed these, will move them as well

**Comment by alex-vv** [comment]
test!

**Review by dimaopen — APPROVED** [review]

**Pull request merged**
