### PR TITLE
od skimm scatter plot #1611

### PR DESCRIPTION
**Pull request by twoface88**
0 scatterplot_simulation_vs_reference

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1651)

#1611 

Data on the image is faked to show how different colors will look like.

### CODE REVIEW

**Comment by wrashid** [comment]
what do the different symbols and colors mean, can they shown (legend)?

**Comment by twoface88** [comment]
0 scatterplot_simulation_vs_reference

**Comment by twoface88** [comment]
0 scatterplot_simulation_vs_reference

**Comment by twoface88** [comment]
0 scatterplot_simulation_vs_reference

@wrashid they are little hard to spot, but there are all 4 kind of colors in this chart

**Comment by colinsheppard** [comment]
@twoface88 can the legend be put in ascending order?

**Comment by twoface88** [comment]
@colinsheppard 

fixed!

0 scatterplot_simulation_vs_reference

**Comment by twoface88** [comment]
Test!

**Comment by twoface88** [comment]
Test!

**Comment by wrashid** [comment]
can we just play with color and not form?

**Comment by twoface88** [comment]
@wrashid 

0 scatterplot_simulation_vs_reference

**Pull request merged**
