### PR TITLE
Write csv and plot to compare euclidean vs. length attribute plot #1697

### PR DESCRIPTION
**Pull request by twoface88**
Write csv and plot to compare euclidean vs. length attribute plot for
matsim network #1697

0 EuclideanVsLengthAttributePlot

csv example:
```
euclidean,length
75.251034,75.065000
75.251034,75.065000
146.482438,146.110000
25.642816,26.915000
12.238537,12.260000
3.537632,3.542000
3.537632,3.542000
3.511446,3.516000
3.511446,3.516000
```

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1754)

### CODE REVIEW

**Comment by twoface88** [comment]
Almost all of the lines in csv are duplicates, but not all of them. Should I remove duplicates?

**Comment by wrashid** [comment]
can you please add linkId in the csv as fist column?

**Comment by twoface88** [comment]
@wrashid 

Done. Example:
```
linkid,euclidean,length
0,75.251034,75.065000
1,75.251034,75.065000
10,146.482438,146.110000
100,25.642816,26.915000
1000,12.238537,12.260000
10000,3.537632,3.542000
10001,3.537632,3.542000
10002,3.511446,3.516000
10003,3.511446,3.516000
10004,36.326556,36.333000
10005,36.326556,36.333000
10006,71.907220,71.964000
10007,71.907220,71.964000
10008,10.370670,10.372000
10009,10.370670,10.372000
1001,12.238537,12.260000
10010,41.402990,41.409000
10011,41.402990,41.409000
10012,85.854820,87.362000
10013,85.854820,87.362000
```

**Comment by twoface88** [comment]
@wrashid 

done. also refactored. example of the csv:
```
linkId,euclidean,length
0,75.251034,75.065000
1,75.251034,75.065000
10,146.482438,146.110000
100,25.642816,26.915000
1000,12.238537,12.260000
10000,3.537632,3.542000
10001,3.537632,3.542000
10002,3.511446,3.516000
10003,3.511446,3.516000
10004,36.326556,36.333000
10005,36.326556,36.333000
```

**Comment by wrashid** [comment]
Test!

**Pull request merged**
