### PR TITLE
Activitysim skims omx format

### PR DESCRIPTION
**Pull request by zneedell**
Tested on production and the output skims look good

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3736)

### CODE REVIEW

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Hey @dimaopen -- no rush, but I'm having some trouble getting this to compile locally (even though it seems to be working on jenkins). Are you able to get the tests to run locally? I'm having trouble figuring out why it's failing -- think you could take a look when you get a chance?

```
java.lang.UnsatisfiedLinkError: /private/var/folders/lz/6syrs9392rx9bkgqpnxc1tdr0000gq/T/hdf52298329236232565282/libjhdf5.jnilib: dlopen(/private/var/folders/lz/6syrs9392rx9bkgqpnxc1tdr0000gq/T/hdf52298329236232565282/libjhdf5.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/lz/6syrs9392rx9bkgqpnxc1tdr0000gq/T/hdf52298329236232565282/libjhdf5.jnilib: mach-o, but wrong architecture
	/private/var/folders/lz/6syrs9392rx9bkgqpnxc1tdr0000gq/T/hdf52298329236232565282/libjhdf5.jnilib: mach-o, but wrong architecture
```

**Comment by dimaopen** [comment]
@zneedell Yes, though I'm running it on a Linux box. If you are at the new Apple m1 chip then you probably need to enable Rosetta mode.
The OMX lib is using http://www.hdfgroup.org/ftp/HDF5/releases/HDF-JAVA/HDF-JAVA-2.8/bin/ these binaries.
I'm not sure that they compiled for the new Mac architecture.

**Comment by dimaopen** [comment]
Maybe we could somehow disable the corresponding unit tests for the mac users?

**Comment by zneedell** [comment]
Ah got it, thanks. I'm actually on an older Intel mac, so it seems strange that it can't find a binary for that -- I'll see if I can figure it out. But if not I'd be fine with disabling the test as long as we think the capability itself is working. Is `BackgroundSkimsCreatorAppSpec` passing for you locally? I can't quite figure out why the test is failing on Jenkins:

```
      java.lang.NullPointerException
      at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
      at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
      at java.lang.Double.parseDouble(Double.java:538)
      at scala.collection.immutable.StringLike.toDouble(StringLike.scala:321)
      at scala.collection.immutable.StringLike.toDouble$(StringLike.scala:321)
      at scala.collection.immutable.StringOps.toDouble(StringOps.scala:33)
      at scripts.BackgroundSkimsCreatorApp$.toCsvSkimRow(BackgroundSkimsCreatorApp.scala:102)
      at scripts.BackgroundSkimsCreatorAppSpec.$anonfun$new$4(BackgroundSkimsCreatorAppSpec.scala:58)

...

      at scripts.BackgroundSkimsCreatorAppSpec.$anonfun$new$3(BackgroundSkimsCreatorAppSpec.scala:58)
      at org.scalatest.concurrent.Futures$.whenReadyImpl(Futures.scala:621)
      at org.scalatest.concurrent.Futures.whenReady(Futures.scala:609)
      at org.scalatest.concurrent.Futures.whenReady$(Futures.scala:608)
      at scripts.BackgroundSkimsCreatorAppSpec.whenReady(BackgroundSkimsCreatorAppSpec.scala:23)
      at scripts.BackgroundSkimsCreatorAppSpec.$anonfun$new$2(BackgroundSkimsCreatorAppSpec.scala:57)

...

scripts.BackgroundSkimsCreatorAppSpec.org$scalatest$wordspec$AnyWordSpecLike$$super$run(BackgroundSkimsCreatorAppSpec.scala:23)
      at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
      at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
      at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
      at scripts.BackgroundSkimsCreatorAppSpec.org$scalatest$BeforeAndAfterAll$$super$run(BackgroundSkimsCreatorAppSpec.scala:23)
```

**Comment by dimaopen** [comment]
I fixed that NPE. It happens because according to the config the results are saved in OMX format which is obviously not readable by the CSV reader.
Though for some reason the output has changed in the test `generate all skims if input is not set.` Not sure why it happened.

**Comment by dimaopen** [comment]
Test!

**Comment by zneedell** [comment]
Thank you! Re-running this in PILATES with the uncompleted trips changes from the other PR -- I'll update if that succeeds

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test now!

**Comment by dimaopen** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
