### PR TITLE
skimmer as attribute of BeamServices

### PR DESCRIPTION
**Pull request by htmlrb**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1559)

### CODE REVIEW

**Comment by htmlrb** [comment]
tests!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
tests!

**Comment by REASY** [comment]
@htmlrb , why do we need to have it as a part of BeamService?
I'm asking because in PR https://github.com/LBNL-UCB-STI/beam/pull/1552/ I removed `setBeamServices` method from BeamSkimmer and made manual control from BeamSim to notify BeamSkimmer (https://github.com/LBNL-UCB-STI/beam/pull/1552/files#diff-daac2f006f1a8b03e4c5a570b8b1ade7R171).

**Comment by JustinPihony** [comment]
@htmlrb I see you closed #!558 - so should this PR be closed also?

**Comment by michaz** [comment]
Superseded by recent events.

**Pull request closed without merging**
