### PR TITLE
Use vehicles.csv input in UrbanSim scenarios

### PR DESCRIPTION
**Pull request by zneedell**
Previously the scenario's PrivateVehicles attribute was being overwritten during scenarioAdjustment when we're using an urbansim scenario (as is the case during pilates). Here's a trial fix, with a hack to hopefully not break anything when freight is turned on

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791)

### CODE REVIEW

**Review by haitamlaarabi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @zneedell)

___
*[`src/main/scala/beam/agentsim/agents/Population.scala` line 109 at r1](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791#-NfO7-Nz9q8EdaV2CuP_:-NfO7-Nz9q8EdaV2CuPa:b23ixhw) ([raw file](https://github.com/LBNL-UCB-STI/beam/blob/85623f815adb64e860680a144e991fb42d8c0642/src/main/scala/beam/agentsim/agents/Population.scala#L109)):*
> ```Scala
>             VehicleInfo(
>               vehicleId = "",
>               vehicleTypeId = vehId.toString,
> ```

Is this supposed to be vehicleTypeId or vehicleId?
___
*[`src/main/scala/beam/sim/BeamHelper.scala` line 325 at r1](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791#-NfO7Yv81dxZr6cQowPC:-NfO7Yv81dxZr6cQowPD:bsv07kh) ([raw file](https://github.com/LBNL-UCB-STI/beam/blob/85623f815adb64e860680a144e991fb42d8c0642/src/main/scala/beam/sim/BeamHelper.scala#L325)):*
> ```Scala
>     val (privateVehicleMap, privateVehicleSoc) = beamConfig.beam.exchange.scenario.source.toLowerCase match {
>       // when reading an urbansim scenario, we read in the vehicles again in ScenarioAdjustment, so there's no need to
>       // bother reading it in now. For now we still do read in freight vehicles, although it's probably cleaner to move
> ```

@dimaopen @nikolayilyin can you actually address this, if possible?
___
*[`src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala` line 60 at r1](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791#-NfO8EcWEJjQz3FDJXrr:-NfO8EcWEJjQz3FDJXrs:blhok6r) ([raw file](https://github.com/LBNL-UCB-STI/beam/blob/85623f815adb64e860680a144e991fb42d8c0642/src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala#L60)):*
> ```Scala
> 
>   def loadScenario(): (Scenario, Boolean) = {
>     // This is a hack for now. When initially building the scenario we skip reading personal vehicles but do read
> ```

@dimaopen @nikolayilyin and this

**Comment by zneedell** [comment]
*[`src/main/scala/beam/agentsim/agents/Population.scala` line 109 at r1](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3791#-NfO7-Nz9q8EdaV2CuP_:-NfRjUPY9uAl7K0vBrVX:bg4yj88) ([raw file](https://github.com/LBNL-UCB-STI/beam/blob/85623f815adb64e860680a144e991fb42d8c0642/src/main/scala/beam/agentsim/agents/Population.scala#L109)):*
<details><summary><i>Previously, haitamlaarabi (Haitam Laarabi) wrote…</i></summary><blockquote>

Is this supposed to be vehicleTypeId or vehicleId?
</blockquote></details>

Ah good catch, thanks!

**Comment by zneedell** [comment]
Test now!

**Comment by zneedell** [comment]
Test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by zneedell** [comment]
Test now!

**Comment by zneedell** [comment]
Test!

**Comment by nikolayilyin** [comment]
test!

**Comment by zneedell** [comment]
Making this a draft for now because I'm noticing some agents getting caught by the stuckfinder. Will try to figure out why

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by zneedell** [comment]
Test now!

**Pull request merged**
