### PR TITLE
Parking stall respects bounding box

### PR DESCRIPTION
**Pull request by REASY**
Production run has errors like:
```
10:37:36.848 [ClusterSystem-akka.actor.default-dispatcher-68] ERROR beam.router.r5.R5RoutingWorker - calcRoute failed
java.util.concurrent.ExecutionException: Boxed Error
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:87)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: assertion failed: Bad coordinate [x=0.0][y=90.0]
	at scala.Predef$.assert(Predef.scala:223)
	at beam.router.model.BeamPath.checkCoordinates(BeamPath.scala:27)
	at beam.router.model.BeamPath.<init>(BeamPath.scala:21)
	at beam.router.r5.R5RoutingWorker$.createBushwackingBeamLeg(R5RoutingWorker.scala:1395)
	at beam.router.r5.R5RoutingWorker$.createBushwackingTrip(R5RoutingWorker.scala:1410)
	at beam.router.r5.R5RoutingWorker.calcRoute(R5RoutingWorker.scala:729)
	at beam.router.r5.R5RoutingWorker$$anonfun$receive$1.$anonfun$applyOrElse$2(R5RoutingWorker.scala:301)
	at beam.sim.metrics.MetricsSupport.latency(MetricsSupport.scala:37)
	at beam.sim.metrics.MetricsSupport.latency$(MetricsSupport.scala:35)
	at beam.router.r5.R5RoutingWorker.latency(R5RoutingWorker.scala:80)
	at beam.router.r5.R5RoutingWorker$$anonfun$receive$1.$anonfun$applyOrElse$1(R5RoutingWorker.scala:302)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	... 5 common frames omitted
```
It also has a lot of errors during route calculation:
```
11:33:48.842 [r5-routing-worker-80] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-57] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-55] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.843 [r5-routing-worker-80] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
11:33:48.859 [r5-routing-worker-80] ERROR com.conveyal.r5.streets.IntHashGrid - Visiting too many spatial index cells.
```
This happens because `lastResortStall` does not respect bounding box

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1899)

### CODE REVIEW

**Comment by michaz** [comment]
@REASY Thanks! Only the ZonalParkingManager needs that parameter, though. The thing that is created in ChoosesMode is, as I'm pretty sure, _only a dummy value_ that is never used. It only uses that lastResort function because it seemed convenient. :-/

Could you try and replace that with something else, please, so the confusing new dependency doesn't get in?

**Comment by REASY** [comment]
@michaz not sure I see how it can be replaced because `var responsePlaceholders` depends on the call to `makeResponsePlaceholders` which depends on the call to `ParkingStall.lastResortStall`. I could remove `def boundingBox: Envelope` from `ChoosesMode` and getting it via `BeamServices` or global static state, but don't think it is better. Any suggestion ?

**Comment by michaz** [comment]
@REASY I take that back, let's keep it like it is. I tried replacing the dummy ParkingStall by null, but apparently it _is_ used in downstream computations (for options that are then not going to be taken).

Will disappear with the grand refactoring of `ChoosesMode`. :-)

**Comment by michaz** [comment]
Just for the record: Please don't use this as an example for how unfortunate it is that you have to pass parameters all the way down to agents. :-D

**Pull request merged**
