### PR TITLE
[Issue-3182] Upgraded scalatest

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #3182 

Needed updates:
https://www.scalatest.org/release_notes/3.1.0

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3182)

### CODE REVIEW

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
Test now!

**Comment by carloscaldas** [comment]
Test!

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
Tests passing:

**Comment by carloscaldas** [comment]
Tests passing

image

**Review by JustinPihony — APPROVED** [review]

**Review by alex-vv — APPROVED** [review]

**Pull request merged**
