### PR TITLE
inm / added visualizations scripts into BEAM to MATSim scripts

### LINKED ISSUE #2274: inm / BEAM to MATSim visualizations images
Put somewhere png images of visualizations. 
Each visualization has its own script and corresponding png image (or group of images).

corresponding PR with visualization scripts is https://github.com/LBNL-UCB-STI/beam/pull/2277

### PR DESCRIPTION
**Pull request by nikolayilyin**
Closes #2274 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2277)

### CODE REVIEW

**Comment by irishwithaxe** [comment]
https://github.com/LBNL-UCB-STI/beam/issues/2274

**Comment by irishwithaxe** [comment]
Test!

**Comment by irishwithaxe** [comment]
Test!

**Comment by nikolayilyin** [comment]
I still think that those changes are not something worth keeping.
Because those are just parameters which was used to generate data for visualizations.

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
