### PR TITLE
Google storage analytic scripts

### LINKED ISSUE #3859: GCP simulations output in spreadsheet
Collect information about outputs (beam and pilates) in google cloud platform bucket, 
format the outputs as spreadsheet and add a tab into [deploy runs spreadsheet](https://docs.google.com/spreadsheets/d/1IV-DmD62vtTTWm0y97TcgpHw5n7ITdEYnETt6QGRw5g/edit#gid=0)

### PR DESCRIPTION
**Pull request by dimaopen**
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3854)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test now!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by dimaopen** [comment]
test!

**Comment by dimaopen** [comment]
test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by dimaopen** [comment]
test!

**Pull request merged**
