### PR TITLE
Warm start fix

### PR DESCRIPTION
**Pull request by dimaopen**
Getting warm start feature working

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3134)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by nikolayilyin — CHANGES_REQUESTED** [review]
a couple nitpicks, the rest lgtm

**Comment by dimaopen** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]

**Pull request merged**
