### PR TITLE
Refactor driving/riding Protocols

### PR DESCRIPTION
**Pull request by colinsheppard**
See issue #165.

### CODE REVIEW

**Comment by michaz** [comment]
Why would an agent get a CompletionNotice (and have to forward it)?

**Comment by michaz** [comment]
Ah, because when an agent thinks it's done with something which was originally prompted by a trigger, it still "replies" with the completion notice to whomever sent the last message which was required for that, which may not be the scheduler. Hmpf.

**Comment by colinsheppard** [comment]
Yes... adding this redirect avoids wasting time tracking down bugs caused simply by forgetting to send the complete to the scheduler versus "sender"

**Comment by michaz** [comment]
Hmhmm, I see.. still don't think it would be wasted time to track this down. I mean, sending messages to the receipient required by the protocol is something we should do without "soft error handling".

**Pull request closed without merging**
