### PR TITLE
Fixed not writing rideHailInitialLocation files

### PR DESCRIPTION
**Pull request by dimaopen**
1. Writing happened before actual data is accumulated. That was fixed in this PR.
2. RHM now writes data in 0.rideHailInitialLocation.name.csv

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3821)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by dimaopen** [comment]
test!

**Pull request merged**
