### PR TITLE
Fdariasm/#600 fix broken tests 4ci

### PR DESCRIPTION
**Pull request by fdariasm**
For the fuel issue for subway, please check changes in Modes.scala and BeamVehicle.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1208)

### CODE REVIEW

**Comment by colinsheppard** [comment]
test!

**Comment by fdariasm** [comment]
@colinsheppard after solving merge conflicts, tests are still passing in local. The error reported in test env is not related with the specs, but I don't really understand it. If the error persists, please let me know how to approach it.

**Comment by JustinPihony** [comment]
This fails locally for me. If you remove/comment the test.dependsOn(spec) in build.gradle then you get a quicker turnaround. The tests are failing because the assertions are wrong..they can be simply changed to the values being output, but I'm not sure if those are right or if there is a bug...

**Comment by fdariasm** [comment]
> This fails locally for me. If you remove/comment the test.dependsOn(spec) in build.gradle then you get a quicker turnaround. The tests are failing because the assertions are wrong..they can be simply changed to the values being output, but I'm not sure if those are right or if there is a bug...

@JustinPihony which tests are failing ?

**Comment by JustinPihony** [comment]
You can see the failing tests from the last run. I bolded the name of the test for the first one:

> 12:04:09 beam.analysis.plots.DeadHeadingGraphTest > **testShouldPassShouldReturnPassengerPerTripInBusForSecondBucket** FAILED
> 12:04:09     java.lang.AssertionError: expected:<6> but was:<1>
> 12:04:09         at org.junit.Assert.fail(Assert.java:91)
> 12:04:09         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:09         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:09         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:09         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:09         at beam.analysis.plots.DeadHeadingGraphTest.testShouldPassShouldReturnPassengerPerTripInBusForSecondBucket(DeadHeadingGraphTest.java:29)
> 12:04:09 
> 12:04:09 beam.analysis.plots.DeadHeadingGraphTest > testShouldPassShouldReturnPassengerPerTripInSubWayForFirstBucket SKIPPED
> 12:04:09 
> 12:04:09 beam.analysis.plots.DeadHeadingGraphTest > testShouldPassShouldReturnPassengerPerTripForCar SKIPPED
> 12:04:09 
> 12:04:09 beam.analysis.plots.DeadHeadingGraphTest > testShouldPassShouldReturnDeadHeadingAllDistanceForSpecificHour FAILED
> 12:04:09     arrays first differed at element [1]; expected:<11> but was:<1>
> 12:04:09         at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
> 12:04:09         at org.junit.Assert.internalArrayEquals(Assert.java:414)
> 12:04:09         at org.junit.Assert.assertArrayEquals(Assert.java:290)
> 12:04:09         at org.junit.Assert.assertArrayEquals(Assert.java:303)
> 12:04:09         at beam.analysis.plots.DeadHeadingGraphTest.testShouldPassShouldReturnDeadHeadingAllDistanceForSpecificHour(DeadHeadingGraphTest.java:62)
> 12:04:09 
> 12:04:09 beam.analysis.plots.DeadHeadingGraphTest > testShouldPassShouldReturnDeadHeadingPassengerPerTripForSpecificHour FAILED
> 12:04:09     arrays first differed at element [1]; expected:<7> but was:<8>
> 12:04:09         at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
> 12:04:09         at org.junit.Assert.internalArrayEquals(Assert.java:414)
> 12:04:09         at org.junit.Assert.assertArrayEquals(Assert.java:290)
> 12:04:09         at org.junit.Assert.assertArrayEquals(Assert.java:303)
> 12:04:09         at beam.analysis.plots.DeadHeadingGraphTest.testShouldPassShouldReturnDeadHeadingPassengerPerTripForSpecificHour(DeadHeadingGraphTest.java:72)
> 12:04:10 
> 12:04:10 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForCRCRCUnitHour FAILED
> 12:04:10     java.lang.NullPointerException
> 12:04:10         at beam.analysis.plots.RealizedModeGraphTest.testShouldPassShouldReturnModeChoseEventOccurrenceForCRCRCUnitHour(RealizedModeGraphTest.java:79)
> 12:04:10 
> 12:04:10 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForCRCUnitHour FAILED
> 12:04:10     java.lang.AssertionError: expected:<37> but was:<8>
> 12:04:10         at org.junit.Assert.fail(Assert.java:91)
> 12:04:10         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:10         at beam.analysis.plots.RealizedModeGraphTest.testShouldPassShouldReturnModeChoseEventOccurrenceForCRCUnitHour(RealizedModeGraphTest.java:65)
> 12:04:10 
> 12:04:10 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventDriveTransitOccurrence FAILED
> 12:04:10     java.lang.AssertionError: expected:<17> but was:<0>
> 12:04:10         at org.junit.Assert.fail(Assert.java:91)
> 12:04:10         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:10         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventDriveTransitOccurrence(ModeChosenGraphTest.java:68)
> 12:04:10 
> 12:04:10 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventRideHailOccurrence FAILED
> 12:04:10     java.lang.AssertionError: expected:<22> but was:<20>
> 12:04:10         at org.junit.Assert.fail(Assert.java:91)
> 12:04:10         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:10         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:10         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventRideHailOccurrence(ModeChosenGraphTest.java:77)
> 12:04:11 
> 12:04:11 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventWalkOccurrence FAILED
> 12:04:11     java.lang.AssertionError: expected:<39> but was:<19>
> 12:04:11         at org.junit.Assert.fail(Assert.java:91)
> 12:04:11         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:11         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventWalkOccurrence(ModeChosenGraphTest.java:86)
> 12:04:11 
> 12:04:11 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventWalkTransitOccurrence FAILED
> 12:04:11     java.lang.AssertionError: expected:<24> but was:<21>
> 12:04:11         at org.junit.Assert.fail(Assert.java:91)
> 12:04:11         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:11         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:11         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventWalkTransitOccurrence(ModeChosenGraphTest.java:95)
> 12:04:12 
> 12:04:12 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForSpecificHour FAILED
> 12:04:12     arrays first differed at element [0]; expected:<2> but was:<21>
> 12:04:12         at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:52)
> 12:04:12         at org.junit.Assert.internalArrayEquals(Assert.java:414)
> 12:04:12         at org.junit.Assert.assertArrayEquals(Assert.java:290)
> 12:04:12         at org.junit.Assert.assertArrayEquals(Assert.java:303)
> 12:04:12         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventOccurrenceForSpecificHour(ModeChosenGraphTest.java:114)
> 12:04:12 
> 12:04:12 beam.analysis.plots.ModeChosenGraphTest > testShouldPassShouldReturnModeChoseEventCarOccurrence FAILED
> 12:04:12     java.lang.AssertionError: expected:<8> but was:<46>
> 12:04:12         at org.junit.Assert.fail(Assert.java:91)
> 12:04:12         at org.junit.Assert.failNotEquals(Assert.java:645)
> 12:04:12         at org.junit.Assert.assertEquals(Assert.java:126)
> 12:04:12         at org.junit.Assert.assertEquals(Assert.java:470)
> 12:04:12         at org.junit.Assert.assertEquals(Assert.java:454)
> 12:04:12         at beam.analysis.plots.ModeChosenGraphTest.testShouldPassShouldReturnModeChoseEventCarOccurrence(ModeChosenGraphTest.java:60)
> 12:04:14 Gradle Test Executor 2 finished executing tests.
> 12:04:14 
> 12:04:14 32 tests completed, 11 failed, 2 skipped
> 12:04:14 Finished generating test XML results (0.03 secs) into: /home/ubuntu/workspace/beam-4ci/build/test-results/test
> 12:04:14 Generating HTML test report...
> 12:04:14 Finished generating test html results (0.036 secs) into: /home/ubuntu/workspace/beam-4ci/build/reports/tests/test
> 12:04:14 :test FAILED
> 12:04:14 :test (Thread[Task worker Thread 2,5,main]) completed. Took 8.189 secs.
> 12:04:14 
> 12:04:14 FAILURE: Build failed with an exception.
> 12:04:14 
> 12:04:14 * What went wrong:
> 12:04:14 Execution failed for task ':test'.
> 12:04:14 > There were failing tests. See the report at: file:///home/ubuntu/workspace/beam-4ci/build/reports/tests/test/index.html
> 12:04:14

**Comment by JustinPihony** [comment]
@colinsheppard @fdariasm Can this branch be deleted, or is it going to spawn a different PR?

**Pull request closed without merging**
