### PR TITLE
Added SimpleRideHailUtilization

### PR DESCRIPTION
**Pull request by REASY**
Simple ridehail utilization which creates the stats from number of passengers to amount of trips. It is implemented as one more `IterationSummaryAnalysis `, so the stats are automatically added to `summaryStats.csv` file. Stats column name are `RideTripsWith0Passengers`, `RideTripsWith1Passengers` and so on. PNGs files are automatically created with name `RideTripsWith0Passengers.png`, `RideTripsWith1Passengers.png` and so on. Example:
image

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1901)

### CODE REVIEW

**Comment by wrashid** [comment]
can we do single graph with stacked bar chart?

**Comment by rajnikantsh** [comment]
Single graph for all iteration

rideHailUtilisation

**Comment by wrashid** [comment]
number labels not needed in stack bar

**Comment by rajnikantsh** [comment]
Updated graph after removing number labels
rideHailUtilisation

**Pull request merged**
