### PR TITLE
sync beam deploy lambda

### PR DESCRIPTION
**Pull request by rajnikantsh**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3352)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by alex-vv** [comment]
it would be good to merge this before https://github.com/LBNL-UCB-STI/beam/pull/3272

**Comment by alex-vv** [comment]
test!

**Comment by alex-vv** [comment]
test!

**Pull request merged**
