### PR TITLE
Xuan/documentation for reposition

### PR DESCRIPTION
**Pull request by Xuan-1998**
Documentation

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3558)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]

**Comment by nikolayilyin** [comment]
test!

**Comment by Xuan-1998** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

**Pull request merged**
