### PR TITLE
Fix so that drivers are not sharing vehicles

### PR DESCRIPTION
**Pull request by JustinPihony**
This should be fixed in another issue so it isn't possible though.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2374)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
Test!

**Comment by JustinPihony** [comment]
Test!

**Comment by REASY** [comment]
@JustinPihony I've approved it. I'm assuming that covering it by regression test is pretty difficult because of special condition when it happens?

**Pull request merged**
