### PR TITLE
#3611_clean-up_of_AWS_storage

### PR DESCRIPTION
**Pull request by edwazhao**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3643)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
Let's rename the notebook to 'preparation to AWS storage cleanup',
Also, I looked at the example of the output and there are wrong rows included, here is an example of wrong aws link - 'https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/*/*', please, check how function reading beamLog process these links.

**Comment by edwazhao** [comment]
> Let's rename the notebook to 'preparation to AWS storage cleanup', Also, I looked at the example of the output and there are wrong rows included, here is an example of wrong aws link - 'https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/*/*', please, check how function reading beamLog process these links.

Hi @nikolayilyin , I have corrected the case for aws link 'https://s3.us-east-2.amazonaws.com/beam-outputs/index.html#output/*/*', and I have updated the file names.
Please check the latest output csv file here: 
[preparation_to_AWS_storage_cleanup.csv](https://github.com/LBNL-UCB-STI/beam/files/9843309/preparation_to_AWS_storage_cleanup.csv)

**Review by nikolayilyin — APPROVED** [review]
looks good to me

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
