### PR TITLE
Made changes in configuration files to create xml.gz

### PR DESCRIPTION
**Pull request by avinashchavanfidel**

### CODE REVIEW

**Comment by avinashchavanfidel** [comment]
The DumpData  expecting xml.gz. so we can make change in DumpData   file to look for only xml file instead of .gz. Please confirm on this.

**Comment by colinsheppard** [comment]
Can you please change file extensions back to ".xml" and then just disable all logging in the following class:

beam.sim.controler.corelisteners.DumpDataAtEndImpl

We will re-enable logging as needed and fix format issues then.

**Comment by colinsheppard** [comment]
Looks great so far. I'm getting the following error:

`[ERROR] [09/06/2017 13:58:37.864] [main] [EventStream(akka://beam-actor-system)] unknown akka.loglevel 
akka.event.Logging$LoggerException: 
	at akka.event.LoggingBus.$anonfun$startDefaultLoggers$1(Logging.scala:103)
	at akka.event.LoggingBus.$anonfun$startDefaultLoggers$1$adapted(Logging.scala:101)
	at scala.Option.getOrElse(Option.scala:121)
	at akka.event.LoggingBus.startDefaultLoggers(Logging.scala:101)
	at akka.event.LoggingBus.startDefaultLoggers$(Logging.scala:99)
	at akka.event.EventStream.startDefaultLoggers(EventStream.scala:28)
	at akka.actor.LocalActorRefProvider.init(ActorRefProvider.scala:667)
	at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:807)
	at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:804)
	at akka.actor.ActorSystemImpl._start(ActorSystem.scala:804)
	at akka.actor.ActorSystemImpl.start(ActorSystem.scala:820)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:245)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:288)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:263)
	at beam.sim.modules.BeamAgentModule$ActorSystemProvider.get(BeamAgentModule.scala:22)
	at beam.sim.modules.BeamAgentModule$ActorSystemProvider.get(BeamAgentModule.scala:20)`

**Comment by avinashchavanfidel** [comment]
Hi Colin,
Could you please explain about how you produce this issue.
I am on branch avn_DumpData_79 and it works well for me .

**Pull request merged**
