### PR TITLE
Hl/#2810 factoring waiting time at depots

### LINKED ISSUE #2810: Factoring waiting time at charging depots

### PR DESCRIPTION
**Pull request by haitamlaarabi**
Resolves #2810 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2876)

### CODE REVIEW

**Comment by haitamlaarabi** [comment]
Test!

**Comment by haitamlaarabi** [comment]
Test!

**Comment by haitamlaarabi** [comment]
Test!

**Comment by REASY** [comment]
test!

**Comment by JustinPihony** [comment]
In case the build falls out of scope:

> 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForCRCUnitHour FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)
> 09:06:19 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForCRCRCUnitHour FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)
> 09:06:19 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnModeChoseEventOccurrenceForRepetitionModes FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)
> 09:06:19 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnReplannigCountModeChoice FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)
> 09:06:19 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnReplannigSequenceCount FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)
> 09:06:19 
> 09:06:19 beam.analysis.plots.RealizedModeGraphTest > testShouldPassShouldReturnReplannigCount FAILED
> 09:06:19     java.lang.NullPointerException
> 09:06:19         at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
> 09:06:19         at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 09:06:19         at java.lang.Double.parseDouble(Double.java:538)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startEvent(EventsReaderXMLv1.java:104)
> 09:06:19         at org.matsim.core.events.EventsReaderXMLv1.startTag(EventsReaderXMLv1.java:85)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader$XmlEventsReader.startTag(MatsimEventsReader.java:89)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.startElement(MatsimXmlParser.java:341)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
> 09:06:19         at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
> 09:06:19         at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.parse(MatsimXmlParser.java:191)
> 09:06:19         at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
> 09:06:19         at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:63)
> 09:06:19         at beam.utils.EventReader$.fromFile(EventReader.scala:83)
> 09:06:19         at beam.utils.EventReader.fromFile(EventReader.scala)
> 09:06:19         at beam.analysis.plots.GraphTestUtil.createDummySimWithXML(GraphTestUtil.java:61)
> 09:06:19         at beam.analysis.plots.RealizedModeGraphTest.setUpCRC(RealizedModeGraphTest.java:54)

**Pull request closed without merging**
