### PR TITLE
write activity type csv in root and iteration directory

### LINKED ISSUE #2921: Write activityType.csv
in each iteration folder, there is activityType.png with activity counts, 
one needs to create activityType.csv in each iteration folder with data used to build activityType.png
then in root folder one needs to create  activityType.csv with the sum of each activity per iteration

### PR DESCRIPTION
**Pull request by rajnikantsh**
Closes #2921 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2930)

### CODE REVIEW

**Comment by rajnikantsh** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test now!

**Comment by JustinPihony** [comment]
test now!

**Pull request merged**
