### PR TITLE
#WIP scoring function updated + code base cleaned up

### LINKED ISSUE #1335: Tests for HH CAVs
This can be modeled after:

PersonWithVehicleSharingSpec

We first want to make sure the protocol is followed if a person belongs to a household with a CAV. For simplicity we can create a 2 person household with an easy to serve schedule, like person 1 moves in morning and person 2 moves midday then person 2 in early evening and person 2 at end of day.

Then we make sure the full itinerary is completed by both people.

### PR DESCRIPTION
**Pull request by htmlrb**
Closes #1335 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1418)

### CODE REVIEW

**Comment by wrashid** [comment]
Test!

**Comment by htmlrb** [comment]
@colinsheppard something went wrong with this branch, changes got overwritten or not merged in the first place. I had to merge master first, resolve conflicts and push again. It is ready to be pulled into master.

**Comment by JustinPihony** [comment]
Just a reminder that WIP can use the new Draft PR while it's still a WIP

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
There are still errors per https://beam-ci.tk/job/beam-forced-prs/797/console

**Comment by wrashid** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Comment by htmlrb** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Comment by htmlrb** [comment]
Test!

**Comment by wrashid** [comment]
Test!

**Comment by JustinPihony** [comment]
test!

**Comment by wrashid** [comment]
test!

**Comment by JustinPihony** [comment]
Test!

**Comment by wrashid** [comment]
test!

**Comment by htmlrb** [comment]
Test!

**Pull request merged**
