### PR TITLE
Simulaliting goods delivery

### LINKED ISSUE #3830: On-demand goods delivery
1. Identify freight payloads that are not assigned to any vehicle or tour and without a carrier ID or carrier ID is a RHM ID.
2. Filter these payloads and convert them into scheduled pickup and drop-off requests for RHM.
3. Use the existing matching algorithm and ride-hail functionality to match food for pickup and drop-off.
4. Implement functionality for ride-hail agents to drive to the pickup location then proceed to the drop-off location to unload for another randomly specified duration.
5. Include tracking in the event file to identify which ride-hail vehicle transported specific payload IDs and the number of payloads, possibly by listing concatenated payload IDs in the path traversal and pickup/drop-off events.
6. Introduce a flag to specify if an RHM operates with a) passengers only, b) passengers and goods, or c) goods only, adjusting the matching algorithm to ensure vehicles matched with goods only receive goods-related queries thereafter, and similarly for passengers (let's not have regular passengers and payloads transported in the same vehicle for now).
7. If implementing a stopping period for ride-hail vehicles before departure proves difficult, consider omitting this feature for now.

### PR DESCRIPTION
**Pull request by dimaopen**
Using plans similar to freight plans. Freight reader also reads these plans. Goods indicator is lack of carrier id.
No real agents (akka actors) are created for goods packages. GoodsDeliveryManager interacts with Ridehail manager with ride-hail requests/responses and generates events.

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3882)

### CODE REVIEW

**Review by haitamlaarabi — APPROVED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3882)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dimaopen)

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by beambot2** [comment]
test!

**Comment by beambot2** [comment]
test now!

**Comment by beambot2** [comment]
test!

**Comment by wrashid** [comment]
test!

**Review by wrashid — APPROVED** [review]
> Reviewed 13 of 24 files at r1, 2 of 6 files at r2, 9 of 10 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3882)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dimaopen)

**Comment by wrashid** [comment]
test!

**Pull request merged**
