### PR TITLE
Make everybody park

### PR DESCRIPTION
**Pull request by michaz**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1218)

### CODE REVIEW

**Comment by michaz** [comment]
#1214

**Comment by michaz** [comment]
Yeah, I know. Task changed to finding the root cause of people not parking.

**Comment by michaz** [comment]
Test!

**Comment by michaz** [comment]
test!

**Comment by michaz** [comment]
test!

**Comment by michaz** [comment]
Test!

**Comment by michaz** [comment]
Test!

**Comment by michaz** [comment]
Test!

**Comment by michaz** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by michaz** [comment]
test!

**Comment by michaz** [comment]
test!

**Pull request merged**
