### PR TITLE
re-enabled tests

### PR DESCRIPTION
**Pull request by carloscaldas**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/430)

### CODE REVIEW

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
test!

**Comment by JustinPihony** [comment]
This now failed ci twice with different tests. Do these ignored tests modify state such that it causes other tests to now fail?

**Comment by wrashid** [comment]
#427 is addressing this issue in more detail

**Pull request closed without merging**
