### PR TITLE
fix the fmt config to what we are using already

### PR DESCRIPTION
**Pull request by JustinPihony**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3235)

### CODE REVIEW

**Comment by JustinPihony** [comment]
The primary change is in .scalafmt.conf and build.gradle. It seems as though we may have missed needed changes due to being marked as "up-to-date" - thus the many other files with minor changes. If any seem incorrect to what we expect then we need to update the scalafmtconf.

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by JustinPihony** [comment]
Thanks for updating against develop @nikolayilyin !

**Pull request merged**
