### PR TITLE
Fix hdf5 issues on Mac OS

### LINKED ISSUE #3831: Fixing failure to load libjhdf5.jnilib on different OS when running ActivitySimOmxWriterSpec locally
```
java.lang.UnsatisfiedLinkError: Can’t load library: /var/folders/6j/kgqvb_h17tx6qkhp71prd9jr0000gq/T/hdf514347871033771246944/libjhdf5.jnilib
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
    at java.base/java.lang.Runtime.load0(Runtime.java:768)
    at java.base/java.lang.System.load(System.java:1854)
    at ncsa.hdf.hdf5lib.H5.loadH5Lib(H5.java:320)
```

```
12:18:09.560 [ScalaTest-1-running-ModeChoiceSpec] ERROR b.s.p.DefaultPopulationAdjustment - Not all agents have person attributes - is attributes file missing ?
java.lang.UnsatisfiedLinkError: Can’t load library: /var/folders/6j/kgqvb_h17tx6qkhp71prd9jr0000gq/T/hdf56415624410489861965/libjhdf5.jnilib
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2638)
    at java.base/java.lang.Runtime.load0(Runtime.java:768)
    at java.base/java.lang.System.load(System.java:1854)
    at ncsa.hdf.hdf5lib.H5.loadH5Lib(H5.java:320)
    at ncsa.hdf.hdf5lib.H5.<clinit>(H5.java:274)
    at ncsa.hdf.hdf5lib.HDF5Constants.<clinit>(HDF5Constants.java:28)
    at omx.hdf5.OmxHdf5File.open(OmxHdf5File.java:82)
    at omx.hdf5.OmxHdf5File.openNew(OmxHdf5File.java:60)
    at omx.OmxFile.openNew(OmxFile.java:102)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$2(ActivitySimOmxWriter.scala:31)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$2$adapted(ActivitySimOmxWriter.scala:29)
    at beam.utils.FileUtils$.using(FileUtils.scala:95)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$1(ActivitySimOmxWriter.scala:29)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.util.Try$.apply(Try.scala:213)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.writeToOmx(ActivitySimOmxWriter.scala:25)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.$anonfun$new$2(ActivitySimOmxWriterSpec.scala:96)
    at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
    at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
    at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.withFixture(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
    at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.runTest(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
    at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
    at scala.collection.immutable.List.foreach(List.scala:431)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
    at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
    at scala.collection.immutable.List.foreach(List.scala:431)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
    at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)
    at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.runTests(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.Suite.run(Suite.scala:1112)
    at org.scalatest.Suite.run$(Suite.scala:1094)
    at [beam.router.skim.urbansim.ActivitySimOmxWriterSpec.org](http://beam.router.skim.urbansim.activitysimomxwriterspec.org/)$scalatest$wordspec$AnyWordSpecLike$$super$run(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
    at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
    at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.run(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.UnsatisfiedLinkError: no jhdf5 in java.library.path: [/Users/haitamlaarabi/Library/Java/Extensions, /Library/Java/Extensions, /Network/Library/Java/Extensions, /System/Library/Java/Extensions, /usr/lib/java, .]
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2678)
    at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
    at java.base/java.lang.System.loadLibrary(System.java:1890)
    at ncsa.hdf.hdf5lib.H5.loadH5Lib(H5.java:347)
    at ncsa.hdf.hdf5lib.H5.<clinit>(H5.java:274)
    at ncsa.hdf.hdf5lib.HDF5Constants.<clinit>(HDF5Constants.java:28)
    at omx.hdf5.OmxHdf5File.open(OmxHdf5File.java:82)
    at omx.hdf5.OmxHdf5File.openNew(OmxHdf5File.java:60)
    at omx.OmxFile.openNew(OmxFile.java:102)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$2(ActivitySimOmxWriter.scala:31)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$2$adapted(ActivitySimOmxWriter.scala:29)
    at beam.utils.FileUtils$.using(FileUtils.scala:95)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.$anonfun$writeToOmx$1(ActivitySimOmxWriter.scala:29)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
    at scala.util.Try$.apply(Try.scala:213)
    at beam.router.skim.urbansim.ActivitySimOmxWriter$.writeToOmx(ActivitySimOmxWriter.scala:25)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.$anonfun$new$2(ActivitySimOmxWriterSpec.scala:96)
    at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.wordspec.AnyWordSpecLike$$anon$3.apply(AnyWordSpecLike.scala:1227)
    at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
    at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.withFixture(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.invokeWithFixture$1(AnyWordSpecLike.scala:1225)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTest$1(AnyWordSpecLike.scala:1237)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
    at org.scalatest.wordspec.AnyWordSpecLike.runTest(AnyWordSpecLike.scala:1237)
    at org.scalatest.wordspec.AnyWordSpecLike.runTest$(AnyWordSpecLike.scala:1219)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.runTest(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$runTests$1(AnyWordSpecLike.scala:1296)
    at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
    at scala.collection.immutable.List.foreach(List.scala:431)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
    at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
    at scala.collection.immutable.List.foreach(List.scala:431)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
    at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
    at org.scalatest.wordspec.AnyWordSpecLike.runTests(AnyWordSpecLike.scala:1296)
    at org.scalatest.wordspec.AnyWordSpecLike.runTests$(AnyWordSpecLike.scala:1295)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.runTests(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.Suite.run(Suite.scala:1112)
    at org.scalatest.Suite.run$(Suite.scala:1094)
    at [beam.router.skim.urbansim.ActivitySimOmxWriterSpec.org](http://beam.router.skim.urbansim.activitysimomxwriterspec.org/)$scalatest$wordspec$AnyWordSpecLike$$super$run(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.wordspec.AnyWordSpecLike.$anonfun$run$1(AnyWordSpecLike.scala:1341)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
    at org.scalatest.wordspec.AnyWordSpecLike.run(AnyWordSpecLike.scala:1341)
    at org.scalatest.wordspec.AnyWordSpecLike.run$(AnyWordSpecLike.scala:1339)
    at beam.router.skim.urbansim.ActivitySimOmxWriterSpec.run(ActivitySimOmxWriterSpec.scala:17)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
```

### PR DESCRIPTION
**Pull request by dimaopen**
Updated OMX-java lib to v2.0.2 which should fix the issue.

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3853)

### CODE REVIEW

**Review by haitamlaarabi — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3853)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @dimaopen)

**Comment by haitamlaarabi** [comment]
test!

**Comment by haitamlaarabi** [comment]
test now!

**Comment by haitamlaarabi** [comment]
test!

**Comment by nikolayilyin** [comment]
test now!

**Comment by haitamlaarabi** [comment]
test!

**Pull request merged**
