### PR TITLE
Fix TollRoutingSpec

### PR DESCRIPTION
**Pull request by michaz**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1012)

### CODE REVIEW

**Comment by michaz** [comment]
test!

**Comment by michaz** [comment]
test!

**Comment by michaz** [comment]
Restores the functionality of the test that was broken in https://github.com/LBNL-UCB-STI/beam/pull/962

**Comment by colinsheppard** [comment]
test!

**Pull request merged**
