### PR TITLE
Jupyter: update of utils, examples and structure 

### PR DESCRIPTION
**Pull request by nikolayilyin**

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Review by dimaopen — APPROVED** [review]

**Pull request merged**
