### PR TITLE
added tests for BikeLanesAdjustment

### LINKED ISSUE #2922: Implement tests for BikeLanesAdjustment

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #2922 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2925)

### CODE REVIEW

**Comment by carloscaldas** [comment]
test now

**Comment by carloscaldas** [comment]
test now

**Review by REASY — APPROVED** [review]

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test now

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
test now

**Comment by carloscaldas** [comment]
test now!

**Comment by carloscaldas** [comment]
test!

**Comment by carloscaldas** [comment]
test now!

**Comment by JustinPihony** [comment]
I think the AMI needs forced to refresh - will do that then re-run the test to see if it speeds things up

**Comment by carloscaldas** [comment]
Test now!

**Pull request merged**
