### PR TITLE
3268 - fix config values pointing to the map

### PR DESCRIPTION
**Pull request by dgm90**
Fix for https://github.com/LBNL-UCB-STI/beam/issues/3268

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3293)

### CODE REVIEW

**Review by JustinPihony — APPROVED** [review]

**Comment by JustinPihony** [comment]
Interestingly I cannot reproduce the CI error locally...

**Comment by dgm90** [comment]
Test!

**Comment by JustinPihony** [comment]
I finally figured it out - it was the renaming. I believe there are test files that use the old name, so if you rename then you have to do a global search in the project. More often at this point re-naming should be treated as an API change and done by creating two values while one is marked as deprecated in some way...or something like that

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
