### PR TITLE
micromobility on sf-light 1k with station data from SF Baywheels

### PR DESCRIPTION
**Pull request by Xuan-1998**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3217)

### CODE REVIEW

**Comment by Xuan-1998** [comment]
@dimaopen calibrating sf-light scenarios to make it more realistic, please review

**Review by dimaopen — COMMENTED** [review]
I didn't quite get where the file 'shared-bike-parking-hubs-test.csv.csv ' is used. For some reason it has 2 csv on the end.

**Comment by Xuan-1998** [comment]
> I didn't quite get where the file 'shared-bike-parking-hubs-test.csv.csv ' is used. For some reason it has 2 csv on the end.

I just uploaded the correct files @dimaopen

**Review by dimaopen — COMMENTED** [review]
Why do you need this test/input/parking/shared-bike-parking-hubs-test.csv ?

**Comment by Xuan-1998** [comment]
> Why do you need this test/input/parking/shared-bike-parking-hubs-test.csv ?

This is the stations for docked shared bikes.

**Comment by dimaopen** [comment]
> This is the stations for docked shared bikes.
Where is it referenced to?

**Comment by Xuan-1998** [comment]
> > This is the stations for docked shared bikes.
> 
> Where is it referenced to?

Yes, BayWheels dock locations:
https://gbfs.baywheels.com/gbfs/en/station_information.json

**Comment by Xuan-1998** [comment]
> > This is the stations for docked shared bikes.
> 
> Where is it referenced to?

And I merging them with the tazs here: https://github.com/LBNL-UCB-STI/beam/tree/develop/test/input/sf-light/shape

**Review by dimaopen — APPROVED** [review]

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

**Review by dimaopen — CHANGES_REQUESTED** [review]
We need to remove the runtime generated files from the source code.

**Comment by Xuan-1998** [comment]
Test!

**Review by dimaopen — APPROVED** [review]

**Pull request merged**
