### PR TITLE
Updated ridehail documentation

### PR DESCRIPTION
**Pull request by dimaopen**
Multiple ridehail manager documentation

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3656)

### CODE REVIEW

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Review by nikolayilyin — CHANGES_REQUESTED** [review]
Is there a place which describe how to configure multiple RH managers in order for each actor in scenario to use only one specific RH manager?

**Comment by dimaopen** [comment]
> Is there a place which describe how to configure multiple RH managers in order for each actor in scenario to use only one specific RH manager?

Added.

**Comment by dimaopen** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
