### PR TITLE
Using RideHailIterationsStatsCollector only if RepositioningManager is REPOSITIONING_LOW_WAITING_TIMES

### PR DESCRIPTION
**Pull request by dimaopen**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3040)

### CODE REVIEW

**Comment by REASY** [comment]
test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test now!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
