### PR TITLE
Don't require beamservices to use OD skimmer

### PR DESCRIPTION
**Pull request by zneedell**
I think this is all we need?

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2340)

### CODE REVIEW

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
> 17:46:16.915 [ClusterSystem-akka.actor.default-dispatcher-21] ERROR akka.actor.OneForOneStrategy - key not found: Car
> java.util.NoSuchElementException: key not found: Car

seems to be happening in test:

> [32mUrbanSimRunSpec:[0m
> [32mUrbanSimRun[0m

and taking the system down.

**Comment by zneedell** [comment]
> > 17:46:16.915 [ClusterSystem-akka.actor.default-dispatcher-21] ERROR akka.actor.OneForOneStrategy - key not found: Car
> > java.util.NoSuchElementException: key not found: Car
> 
> seems to be happening in test:
> 
> > �[32mUrbanSimRunSpec:�[0m
> > �[32mUrbanSimRun�[0m
> 
> and taking the system down.

Yeah this is weird--I can't reproduce locally. Do you think there's a chance it's a Jenkins thing or more likely just a bug in the branch?

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Comment by zneedell** [comment]
Test!

**Pull request closed without merging**
