### PR TITLE
change cav automation level

### LINKED ISSUE #1848: beamVehicle - change isCAV to automationLevel==5

### PR DESCRIPTION
**Pull request by rajnikantsh**
Fixes #1848 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1849)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by rajnikantsh** [comment]
Test!

**Comment by rajnikantsh** [comment]
Test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by michaz** [comment]
Don't know how live this is, but just wanted to add that this property ( `isCav`) doesn't currently seem to be used for a lot. E.g. Households have a different opinion about what a CAV is.

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
This is such a simple change - would it be the reason for not being able to complete tests, or is there maybe something else at hand? Maybe it needs merged with develop again?

**Pull request merged**
