### PR TITLE
StuckFinder: Better stuck detection

### PR DESCRIPTION
**Pull request by REASY**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/668)

### CODE REVIEW

**Comment by colinsheppard** [comment]
I'm assuming you will be adding the other strategy for stuck detection in this PR, let me know when that's done and I'll complete the review.

**Comment by REASY** [comment]
## Prod run on diffusion-and-rh2transit-base.conf:
### Iteration 0:
```
Max number of trigger messages per actor type
        RideHailAgent => 187
        RideHailManager => 108261
        TransitDriverAgent => 277
        Population => 6839
```

**Comment by REASY** [comment]
## sf-light-5k run:
### Iteration 0:
```
Max number of trigger messages per actor type
	RideHailAgent => 53
	RideHailManager => 108335
	TransitDriverAgent => 229
	Population => 199
```

### Iteration 1:
```
Max number of trigger messages per actor type
	RideHailAgent => 61
	RideHailManager => 108335
	TransitDriverAgent => 229
	Population => 189
```

**Comment by REASY** [comment]
## Prod run on diffusion-and-rh2transit-base.conf:
### Iteration 0:
```
Max number of trigger messages per actor type
        RideHailAgent => 23
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 11
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 11
        RideHailManager => 108356
                class beam.agentsim.agents.ridehail.RideHailManager$RideHailAllocationManagerTimeout => 361
                class beam.agentsim.agents.ridehail.RideHailManager$BufferedRideHailRequestsTimeout => 107995
        TransitDriverAgent => 21
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 10
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 10
        Population => 35
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.PersonAgent$ActivityEndTrigger => 5
                class beam.agentsim.agents.PersonAgent$PersonDepartureTrigger => 4
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 8
                class beam.agentsim.agents.PersonAgent$ActivityStartTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegEndTrigger => 4
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegStartTrigger => 4
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 8

```

**Comment by REASY** [comment]
## sf-light-5k run:
### Iteration 0:
```
Max number of trigger messages per actor type
	RideHailAgent => 21
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 10
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 10
	RideHailManager => 108335
		class beam.agentsim.agents.ridehail.RideHailManager$BufferedRideHailRequestsTimeout => 107974
		class beam.agentsim.agents.ridehail.RideHailManager$RideHailAllocationManagerTimeout => 361
	TransitDriverAgent => 23
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 11
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 11
	Population => 19
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.PersonAgent$ActivityStartTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegEndTrigger => 2
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 4
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegStartTrigger => 2
		class beam.agentsim.agents.PersonAgent$PersonDepartureTrigger => 2
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 4
		class beam.agentsim.agents.PersonAgent$ActivityEndTrigger => 3
```

### Iteration 1:
```
Max number of trigger messages per actor type
	RideHailAgent => 5
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 2
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 2
	RideHailManager => 108335
		class beam.agentsim.agents.ridehail.RideHailManager$BufferedRideHailRequestsTimeout => 107974
		class beam.agentsim.agents.ridehail.RideHailManager$RideHailAllocationManagerTimeout => 361
	TransitDriverAgent => 49
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 24
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 24
	Population => 39
		class beam.agentsim.agents.InitializeTrigger => 1
		class beam.agentsim.agents.PersonAgent$ActivityStartTrigger => 1
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegEndTrigger => 2
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 12
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$NotifyLegStartTrigger => 2
		class beam.agentsim.agents.PersonAgent$PersonDepartureTrigger => 4
		class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 12
		class beam.agentsim.agents.PersonAgent$ActivityEndTrigger => 5
```

**Comment by REASY** [comment]
## After fixing bug with incorrect counting of max messages:
```
Max number of trigger messages per actor type
        RideHailAgent => 75
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 37
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 37
        RideHailManager => 108065
                class beam.agentsim.agents.ridehail.RideHailManager$RideHailAllocationManagerTimeout => 361
                class beam.agentsim.agents.ridehail.RideHailManager$BufferedRideHailRequestsTimeout => 107704
        TransitDriverAgent => 277
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 138
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 138
        Population => 127
                class beam.agentsim.agents.PersonAgent$ActivityStartTrigger => 1
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$AlightVehicleTrigger => 12
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$BoardVehicleTrigger => 12
                class beam.agentsim.agents.InitializeTrigger => 1
                class beam.agentsim.agents.PersonAgent$ActivityEndTrigger => 11
                class beam.agentsim.agents.PersonAgent$PersonDepartureTrigger => 10
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$EndLegTrigger => 40
                class beam.agentsim.agents.modalbehaviors.DrivesVehicle$StartLegTrigger => 40
```

**Comment by REASY** [comment]
It's not that straightforward to write one `defaultMaxNumberOfMessages` which will fit all actors because, for example, `RideHailManager ` sends **107704** `BufferedRideHailRequestsTimeout `.
I think to leave is at is. I've added `checkMaxNumberOfMessagesEnabled` flag to control stuck detection via max number of messages. It's ready to be merged,  @colinsheppard

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by REASY** [comment]
On my machine all tests are passed:
image

**Pull request merged**
