### PR TITLE
disabled failed test in CarSpecSharing

### PR DESCRIPTION
**Pull request by carloscaldas**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2974)

### CODE REVIEW

**Review by REASY — APPROVED** [review]

**Comment by carloscaldas** [comment]
Test now!

**Review by REASY — CHANGES_REQUESTED** [review]
According to Jenkins, develop branch is green: https://beam-ci.tk/job/develop/

We need to dig into the actual problem.

**Comment by JustinPihony** [comment]
Should we close this and open an issue instead?

**Comment by carloscaldas** [comment]
test was fixed. no needed anymore

**Pull request closed without merging**
