### PR TITLE
Turn Google into empty object if not enabled

### LINKED ISSUE #3358: Google speed API: don't write extra logs when disabled.
Even when work with Google speed API is disabled, there are log entries in the beamLog.out file
```TravelTimeGoogleStatistic - Date in the past: 2020-10-14, using a future one```

One needs to make sure this written out only when google sped api is enabled.

### PR DESCRIPTION
**Pull request by JustinPihony**
Resolves #3358

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3401)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
