### PR TITLE
fix check docker is running for CCHRoutingAssignment

### PR DESCRIPTION
**Pull request by dgm90**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3321)

### CODE REVIEW

**Comment by dgm90** [comment]
test!

**Comment by dgm90** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
LGTM

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Comment by dgm90** [comment]
Test!

**Pull request merged**
