### PR TITLE
Fdariasm/mode related tests

### PR DESCRIPTION
**Pull request by fdariasm**
Tests updated to run different tests for each mode choice. Pending for ModeChoiceMultinomialLogit (generates different output on every execution) and ModeChoiceUniformRandom (BEAM hangs during run).

### CODE REVIEW

**Comment by fdariasm** [comment]
@colinsheppard agentsim branch merged into this one, tests for existing classes updated as the output for modeChoices changed, and tests for new classes added.

**Comment by colinsheppard** [comment]
@fdariasm I think it's ok, to close this PR, but let me know... I haven't completed the merge due to the conflicts but the fact that earlier today I merged integration-testing-conflict-res into cjrs/agentsim-lccm probably means this PR is now unnecessary.

**Comment by colinsheppard** [comment]
Hi @fdariasm can you please let me know about my previous question?

**Comment by fdariasm** [comment]
@colinsheppard, yes this PR is unnecessary as all tests were moved to integration-testing-conflict-res and that's the branch I'm working on.

**Comment by colinsheppard** [comment]
Thanks!

**Pull request closed without merging**
