### PR TITLE
Fix object comparison bug

### LINKED ISSUE #3194: Comparing different types (bug)
class `BeamVehicle`

code:
```scala
  def connectToChargingPoint(startTick: Int): Unit = {
    if (beamVehicleType.primaryFuelType == Electricity || beamVehicleType.secondaryFuelType == Electricity) {
```

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #3194 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3195)

### CODE REVIEW

**Review by rajnikantsh — APPROVED** [review]
LGTM

**Comment by rajnikantsh** [comment]
@carloscaldas can you check this also https://github.com/LBNL-UCB-STI/beam/blob/10f4cf0c806fe65319c9a43685765f859060cefd/src/main/scala/beam/agentsim/agents/ridehail/RideHailManager.scala#L1724 it also seems unrelated object compare

**Comment by carloscaldas** [comment]
Test now!

**Review by johanneshiry — APPROVED** [review]

**Comment by carloscaldas** [comment]
Test now!

**Pull request merged**
