### PR TITLE
skimming energy consumption for passengers

### PR DESCRIPTION
**Pull request by htmlrb**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1613)

### CODE REVIEW

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by htmlrb** [comment]
test!

**Comment by wrashid** [comment]
Test!

**Pull request merged**
