### PR TITLE
#60 Updates gtfs files for beamville

### PR DESCRIPTION
**Pull request by fdariasm**
GTFS updated, bus stops at every intersection.

### CODE REVIEW

**Comment by colinsheppard** [comment]
When I run (after fixing the "BUS not supported" error) I only see a single path traversal per transit vehicle, not 5 as I would expect, please troubleshoot:

	```
<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-1" departure_time="22201.0" mode="bus" links="Vector(284),"  />
	<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-1" departure_time="22201.0" mode="bus" links="Vector(20),"  />
	<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-1" departure_time="22201.0" mode="bus" links="Vector(0),"  />
	<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-1" departure_time="22201.0" mode="bus" links="Vector(312),"  />
	<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-1" departure_time="22201.0" mode="bus" links="Vector(344),"  />
	<event time="22201.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-1" departure_time="22201.0" mode="bus" links="Vector(44),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-2" departure_time="22801.0" mode="bus" links="Vector(344),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-2" departure_time="22801.0" mode="bus" links="Vector(312),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-2" departure_time="22801.0" mode="bus" links="Vector(0),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-2" departure_time="22801.0" mode="bus" links="Vector(44),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-2" departure_time="22801.0" mode="bus" links="Vector(20),"  />
	<event time="22801.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-2" departure_time="22801.0" mode="bus" links="Vector(284),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-3" departure_time="23401.0" mode="bus" links="Vector(44),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-3" departure_time="23401.0" mode="bus" links="Vector(20),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-3" departure_time="23401.0" mode="bus" links="Vector(344),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-3" departure_time="23401.0" mode="bus" links="Vector(312),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-3" departure_time="23401.0" mode="bus" links="Vector(284),"  />
	<event time="23401.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-3" departure_time="23401.0" mode="bus" links="Vector(0),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-4" departure_time="24001.0" mode="bus" links="Vector(344),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-4" departure_time="24001.0" mode="bus" links="Vector(44),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-4" departure_time="24001.0" mode="bus" links="Vector(0),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-4" departure_time="24001.0" mode="bus" links="Vector(20),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-4" departure_time="24001.0" mode="bus" links="Vector(312),"  />
	<event time="24001.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-4" departure_time="24001.0" mode="bus" links="Vector(284),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-5" departure_time="24601.0" mode="bus" links="Vector(20),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-5" departure_time="24601.0" mode="bus" links="Vector(312),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-5" departure_time="24601.0" mode="bus" links="Vector(0),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-5" departure_time="24601.0" mode="bus" links="Vector(44),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-5" departure_time="24601.0" mode="bus" links="Vector(344),"  />
	<event time="24601.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-5" departure_time="24601.0" mode="bus" links="Vector(284),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B2-WEST-6" departure_time="25201.0" mode="bus" links="Vector(20),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B2-EAST-6" departure_time="25201.0" mode="bus" links="Vector(312),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B3-WEST-6" departure_time="25201.0" mode="bus" links="Vector(20),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B3-EAST-6" departure_time="25201.0" mode="bus" links="Vector(284),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B1-EAST-6" departure_time="25201.0" mode="bus" links="Vector(344),"  />
	<event time="25201.0" type="PathTraversal" vehicle="bus.gtfs:B1-WEST-6" departure_time="25201.0" mode="bus" links="Vector(44),"  />

```

**Comment by colinsheppard** [comment]
@fdariasm  

I fixed the issue in our old beamville GTFS here: 0424226

You will need to propagate this fix to your changed schedules and/or redo the fix entirely.

**Comment by fdariasm** [comment]
@colinsheppard I updated stop_sequence field for bus and train in stop_times.txt files, that's the issue I saw from the commits you referenced, but I still see same output. Can you please help me check

**Comment by colinsheppard** [comment]
@fdariasm what appeared to be missing was compressing the new GTFS data into zip archives and then deleting the old network.dat file so that R5 will rebuild the network. It works now.

**Pull request merged**
