### PR TITLE
Issue 936 - Gradle task generating documentation

### PR DESCRIPTION
**Pull request by carloscaldas**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/946)

### CODE REVIEW

**Comment by carloscaldas** [comment]
@colinsheppard the requested changes were already made. please review it

**Comment by carloscaldas** [comment]
@colinsheppard The change you requested was made. Also fixed Malformed table in `outputs.rst`

**Comment by colinsheppard** [comment]
@carloscaldas this is **almost** there. I think the markdown formatting in my previous comment hid what I was asking for. Please make the header above the tables should like like this (i.e. I want the filename to be used as the title (with the word "File: " and the class name to come underneath). This is documentation for users so the classname is almost meaningless to them, the file name is important because this is what they see when they run BEAM:
 
```

File: modeChoice.csv
---------------------

Class name: ModeChosenAnalysisObject


```

**Comment by colinsheppard** [comment]
Also, please rearrange the column order so that field comes first!

**Comment by carloscaldas** [comment]
Hi @colinsheppard. There is a problem with this approach (adding the file as part of the title). Some Objects like `ModeChosenAnalysisObject` have more than one file depending on the field. How should solve this situation?

**Comment by carloscaldas** [comment]
@colinsheppard now is grouped by `file`. In case you want to remove the field `className` from the tables just need to change the line below
https://github.com/LBNL-UCB-STI/beam/blob/13b6db019af0530c69457e476c39eb1ea7eeccaf/src/main/scala/beam/docs/GenerateDocumentationTask.scala#L63

**Pull request merged**
