### PR TITLE
Xuan/enable carusage for scenarios

### PR DESCRIPTION
**Pull request by Xuan-1998**
Creating limit on CarUsage which will come in handy for scenario runs in different cities.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3377)

### CODE REVIEW

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

**Review by JustinPihony — APPROVED** [review]

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by Xuan-1998** [comment]
Test didn’t pass because of the `nextActivity(data).get` is getting none?

**Comment by JustinPihony** [comment]
No, it is because:

> 23:50:11 PersonAgentSpec:
> 23:50:11 A PersonAgent
> ...
> 3:50:11 - should demonstrate a complete trip, throwing MATSim events *** FAILED *** (1 second, 402 milliseconds)
> 23:50:11   java.lang.AssertionError: assertion failed: expected class beam.agentsim.agents.ridehail.RideHailRequest, found class beam.agentsim.scheduler.BeamAgentScheduler$CompletionNotice (CompletionNotice(0,Vector()))
> 23:50:11   at scala.Predef$.assert(Predef.scala:223)
> 23:50:11   at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:570)
> 23:50:11   at akka.testkit.TestKitBase.expectMsgType(TestKit.scala:541)
> 23:50:11   at akka.testkit.TestKitBase.expectMsgType$(TestKit.scala:540)
> 23:50:11   at beam.agentsim.agents.PersonAgentSpec.expectMsgType(PersonAgentSpec.scala:43)
> 23:50:11   at beam.agentsim.agents.PersonAgentSpec.$anonfun$new$5(PersonAgentSpec.scala:203)
> 23:50:11   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
> 23:50:11   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
> 23:50:11   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
> 23:50:11   at org.scalatest.Transformer.apply(Transformer.scala:22)


Although I think that is due to:

> 23:43:08 04:43:08.814 [PersonAgentSpec-akka.actor.default-dispatcher-5] ERROR akka.actor.OneForOneStrategy - null
> 23:43:08 java.lang.NullPointerException: null
> 23:43:08 	at beam.agentsim.agents.PersonAgent.beam$agentsim$agents$PersonAgent$$canUseCars(PersonAgent.scala:511)
> 23:43:08 	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:503)
> 23:43:08 	at beam.agentsim.agents.PersonAgent$$anonfun$3.applyOrElse(PersonAgent.scala:472)
> 23:43:08 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
> 23:43:08 	at akka.actor.FSM.processEvent(FSM.scala:804)
> 23:43:08 	at akka.actor.FSM.processEvent$(FSM.scala:801)
> 23:43:08 	at beam.agentsim.agents.PersonAgent.akka$actor$BeamLoggingFSM$$super$processEvent(PersonAgent.scala:249)
> 23:43:08 	at akka.actor.BeamLoggingFSM.processEvent(BeamLoggingFSM.scala:69)
> 23:43:08 	at akka.actor.BeamLoggingFSM.processEvent$(BeamLoggingFSM.scala:44)
> 23:43:08 	at beam.agentsim.agents.PersonAgent.processEvent(PersonAgent.scala:249)
> 23:43:08 	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:798)
> 23:43:08 	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:793)
> 23:43:08 	at akka.actor.Actor.aroundReceive(Actor.scala:535)
> 23:43:08 	at akka.actor.Actor.aroundReceive$(Actor.scala:533)
> 23:43:08 	at beam.agentsim.agents.PersonAgent.aroundReceive(PersonAgent.scala:249)
> 23:43:08 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:577)
> 23:43:08 	at akka.actor.ActorCell.invoke(ActorCell.scala:547)
> 23:43:08 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
> 23:43:08 	at akka.dispatch.Mailbox.run(Mailbox.scala:231)
> 23:43:08 	at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
> 23:43:08 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 23:43:08 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 23:43:08 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 23:43:08 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)

So, I think it has to do with the `trainStopQuadTree` being `null` and the code not handling it. Is it valid for this to be `null`?

**Comment by JustinPihony** [comment]
This was caused by the excludeModes changes - as I removed that and it worked. I'm still debugging, but have it down to https://github.com/LBNL-UCB-STI/beam/pull/3377/files#diff-940cd21d65d4ec3f2f9c49c5aaf9753e3b2b4d030fabd7a7d4ed861a8eda857fR502 currently.


Update: It is not necessarily the excludeModes itself, but that the `canUseCars` being used in this flow without handling `null` coordinates. It is an easy fix, however we should also run against some prod scenario before merging also.

**Comment by JustinPihony** [comment]
test!

**Pull request merged**
