### PR TITLE
Remove throwing error from input consistency

### PR DESCRIPTION
**Pull request by rajnikantsh**
implementation of https://github.com/LBNL-UCB-STI/beam/issues/3328

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3339)

### CODE REVIEW

**Comment by rajnikantsh** [comment]
test!

**Comment by JustinPihony** [comment]
I commented on the main issue, questioning this route versus handling default/empty

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Review by JustinPihony — APPROVED** [review]

**Pull request merged**
