### PR TITLE
Route dumper fix

### LINKED ISSUE #3383: RouteDumper - fix writing RoutingResponseEvent
There are 2 errors in `beamLog.out` when a simulation is run with `beam.outputs.writeR5RoutesInterval = 1` set in `beam.conf`. This happens in this branch https://github.com/LBNL-UCB-STI/beam/tree/art/new-york-only-code

One is `IllegalArgumentException`, happening in AvroWriteSupport.
```
18:06:40.774 [Events-0] ERROR o.m.core.events.EventsManagerImpl - Could not handle event '  <event time="1295.0" type="RoutingResponseEvent"  />' by handler 'eventClass: class org.matsim.api.core.v01.events.Event, eventHandler: beam.router.r5.RouteDumper@26c87e66'. Error: Cannot write unless collection or array: java.lang.String
java.lang.IllegalArgumentException: Cannot write unless collection or array: java.lang.String
    at org.apache.parquet.Preconditions.checkArgument(Preconditions.java:53)
    at org.apache.parquet.avro.AvroWriteSupport$ListWriter.writeList(AvroWriteSupport.java:398)
    at org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:355)
    at org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)
    at org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)
    at org.apache.parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:165)
    at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
    at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:299)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$4(RouteDumper.scala:65)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$3(RouteDumper.scala:65)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$3$adapted(RouteDumper.scala:64)
    at scala.Option.foreach(Option.scala:407)
    at beam.router.r5.RouteDumper.handleEvent(RouteDumper.scala:64)
    at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:354)
    at org.matsim.core.events.EventsManagerImpl.handle(EventsManagerImpl.java:245)
    at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:231)
    at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139)
    at org.matsim.core.events.ProcessEventThread.run(ProcessEventThread.java:93)
    at java.lang.Thread.run(Thread.java:748)
```
A quick debug session has shown that value `""` can not be written
image
Probably because of [these lines](https://github.com/LBNL-UCB-STI/beam/blob/b6cb33a8710777eff4bfcfec822a7de0ded735bc/src/main/scala/beam/router/r5/RouteDumper.scala#L273-L274)

===========================================================================================

Another issue is 
```
18:06:41.208 [Events-0] ERROR o.m.core.events.EventsManagerImpl - Could not handle event '  <event time="1971.0" type="RoutingResponseEvent"  />' by handler 'eventClass: class org.matsim.api.core.v01.events.Event, eventHandler: beam.router.r5.RouteDumper@26c87e66'. Error: 2
java.lang.ArrayIndexOutOfBoundsException: 2
    at org.apache.parquet.io.MessageColumnIO$MessageColumnIORecordConsumer.addInteger(MessageColumnIO.java:439)
    at org.apache.parquet.avro.AvroWriteSupport.writeValueWithoutConversion(AvroWriteSupport.java:323)
    at org.apache.parquet.avro.AvroWriteSupport.writeValue(AvroWriteSupport.java:278)
    at org.apache.parquet.avro.AvroWriteSupport.writeRecordFields(AvroWriteSupport.java:191)
    at org.apache.parquet.avro.AvroWriteSupport.write(AvroWriteSupport.java:165)
    at org.apache.parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:128)
    at org.apache.parquet.hadoop.ParquetWriter.write(ParquetWriter.java:299)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$4(RouteDumper.scala:65)
    at java.util.ArrayList.forEach(ArrayList.java:1259)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$3(RouteDumper.scala:65)
    at beam.router.r5.RouteDumper.$anonfun$handleEvent$3$adapted(RouteDumper.scala:64)
    at scala.Option.foreach(Option.scala:407)
    at beam.router.r5.RouteDumper.handleEvent(RouteDumper.scala:64)
    at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:354)
    at org.matsim.core.events.EventsManagerImpl.handle(EventsManagerImpl.java:245)
    at org.matsim.core.events.EventsManagerImpl.computeEvent(EventsManagerImpl.java:231)
    at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139)
    at org.matsim.core.events.ProcessEventThread.run(ProcessEventThread.java:93)
    at java.lang.Thread.run(Thread.java:748)
```

For now the `writeR5RoutesInterval` [is disabled ](https://github.com/LBNL-UCB-STI/beam-data-newyork/commit/3c65951fbd58c63f3fb2dc445cb579ad33bc94b3)

### PR DESCRIPTION
**Pull request by alex-vv**
Fixes #3383 

Note this PR is for `art/new-york-only-code` branch since issue is present there

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3412)

### CODE REVIEW

**Comment by alex-vv** [comment]
test!

**Comment by alex-vv** [comment]
test!

**Comment by alex-vv** [comment]
test!

**Comment by dgm90** [comment]
Is this fix for both issues mentioned in https://github.com/LBNL-UCB-STI/beam/issues/3383 ?
If yes - should we enable writeR5RoutesInterval back? I mean revert this commit https://github.com/LBNL-UCB-STI/beam-data-newyork/commit/3c65951fbd58c63f3fb2dc445cb579ad33bc94b3

**Review by dgm90 — APPROVED** [review]

**Comment by alex-vv** [comment]
> Is this fix for both issues mentioned in #3383 ? If yes - should we enable writeR5RoutesInterval back? I mean revert this commit [LBNL-UCB-STI/beam-data-newyork@3c65951](https://github.com/LBNL-UCB-STI/beam-data-newyork/commit/3c65951fbd58c63f3fb2dc445cb579ad33bc94b3)

yes this is a fix for both issues, I think it makes sense to enable `writeR5RoutesInterval` back, I will do that after merging this PR

**Pull request merged**
