### PR TITLE
Jupyter: notebook to adjust GTFS time and timezone and to downsample scenario based on shape file

### PR DESCRIPTION
**Pull request by nikolayilyin**
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3775)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test!

**Review by HoneyTauOverTwo — APPROVED** [review]
lgtm

**Comment by HoneyTauOverTwo** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Pull request merged**
