### PR TITLE
a fix for reading of big urbansim_v2 scenarios

### PR DESCRIPTION
**Pull request by nikolayilyin**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3258)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
the fix is already in develop

**Review by dimaopen — COMMENTED** [review]
These values were increased in some other PR.

**Pull request closed without merging**
