### PR TITLE
Add Optimizer as experimental

### PR DESCRIPTION
**Pull request by JustinPihony**
I realized I forgot to push this through so that Haitam can do what he needed. Recall that the stats from the more complex, standalone run are here - https://docs.google.com/spreadsheets/d/1GrjWdgtIuaaF9U-7ToMfPxEFeI56PTSFJQGEA4yACFc/edit#gid=0

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1045)

### CODE REVIEW

**Comment by colinsheppard** [comment]
failed on FMT...

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Pull request merged**
