### PR TITLE
this will fix human ridehail access to charging

### PR DESCRIPTION
**Pull request by haitamlaarabi**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3140)

### CODE REVIEW

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by haitamlaarabi** [comment]
Test now!

**Review by nikolayilyin — APPROVED** [review]
LGTM

**Review by nikolayilyin — APPROVED** [review]

**Pull request merged**
