### PR TITLE
random seed in beam-template.conf

### PR DESCRIPTION
**Pull request by g-derzhavets**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3520)

### CODE REVIEW

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Review by nikolayilyin — CHANGES_REQUESTED** [review]
The name of new parameter in src/main/resources/beam-template.conf is different from the name in src/main/scala/beam/sim/config/BeamConfig.scala, this should not be happening

**Comment by g-derzhavets** [comment]
Test!

**Comment by g-derzhavets** [comment]
Test!

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Pull request merged**
