### PR TITLE
Remove rounding of link travel times

### LINKED ISSUE #3361: Remove rounding of link travel times
In order to have a more precise agentsim we need to remove rounding of travel times calculated for links during routing. https://github.com/LBNL-UCB-STI/beam/blob/bd7f812db736f4a5b8020badb33342479c6d5d73/src/main/scala/beam/router/r5/CarWeightCalculator.scala#L55

### PR DESCRIPTION
**Pull request by dimaopen**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3362)

### CODE REVIEW

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by dimaopen** [comment]
Test!

**Comment by dimaopen** [comment]
Test!

**Pull request merged**
