### PR TITLE
draw from binomial for last stall when parking is scaled down

### PR DESCRIPTION
**Pull request by zneedell**
deals with rounding effects for small number of parking stalls. Now the total number of stalls created should ~= scaling factor * number of stalls in the input file.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2186)

### CODE REVIEW

**Comment by zneedell** [comment]
fixes #2109

**Comment by zneedell** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
@zneedell This needs the tests fixed up to match the changes - that's what is failing to compile

**Comment by zneedell** [comment]
test!

**Comment by JustinPihony** [comment]
@zneedell This is all green, but will leave to you to merge :)

**Pull request merged**
