### PR TITLE
Update users.rst

### PR DESCRIPTION
**Pull request by Ummul-Khair**
Typographical error

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3589)

### CODE REVIEW

**Review by Ummul-Khair — COMMENTED** [review]
Correction valid.

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
There is the wrong base branch used: the correct base branch is 'develop', not 'master'.

**Pull request closed without merging**
