### PR TITLE
create tests for summary stats

### LINKED ISSUE #1091: create tests for summary stats

### PR DESCRIPTION
**Pull request by zishanbilal**
Fixes #1091

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1102)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by zishanbilal** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Comment by colinsheppard** [comment]
@zishanbilal this has a compile error:

https://beam-ci.tk/job/beam-forced-prs/399/console

**Pull request merged**
