### PR TITLE
Add Critical Actor trait and use in ZPM

### LINKED ISSUE #2311: Create a trait which can be used to crash the entire system upon exception
From Slack:
> in my experience, throwing an exception from within ZonalParkingManager doesn't stop the simulation.

### PR DESCRIPTION
**Pull request by JustinPihony**
Closes #2311

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2312)

### CODE REVIEW

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by robfitzgerald** [comment]
right, it seems there is a set of actors which should never fail in a simulation. should the R5RoutingWorkers, RideHailManager, and BeamAgentScheduler also receive this trait?

**Pull request merged**
