### PR TITLE
Emissions fix for RH

### PR DESCRIPTION
**Pull request by nikolayilyin**
Add missing emissions for RH for first link in PathTraversal event.
Add missing IDLE emissions for RH after ShiftStart event and before PathTraversal event.
Add missing IDLE emissions for RH between two PathTraversal event, if there were no other activities.
Add missing IDLE emissions for RH after PathTraversal event and before ShiftEnd event.
Add test to check if RH IDLE time and all links from RH PathTraversal event are present in generated emissions skims.

- - -
This change is [Reviewable](https://reviewable.io/reviews/LBNL-UCB-STI/beam/3901)

### CODE REVIEW

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Comment by nikolayilyin** [comment]
test!

**Review by haitamlaarabi — APPROVED** [review]
Looks good

**Comment by dimaopen** [comment]
Test!

**Comment by haitamlaarabi** [comment]
Test now!

**Comment by beambot2** [comment]
test!

**Comment by beambot2** [comment]
test now!

**Comment by beambot2** [comment]
test!

**Pull request merged**
