### PR TITLE
Cs/bsd release

### PR DESCRIPTION
**Pull request by colinsheppard**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1226)

### CODE REVIEW

**Comment by colinsheppard** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by colinsheppard** [comment]
test!

**Pull request merged**
