### PR TITLE
Project: Use forked matsim

### PR DESCRIPTION
**Pull request by REASY**
Use matsim `0.10.1-beam-6` from https://github.com/wrashid/matsim

This will solve https://github.com/LBNL-UCB-STI/beam/issues/1636

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1549)

### CODE REVIEW

**Comment by JustinPihony** [comment]
Just a reminder for the future - you can create a draft PR rather than rely on the WIP label

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Comment by REASY** [comment]
test!

**Pull request merged**
